# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\kera_\Documents\GitHub\EHRTeam\QtUI.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(653, 594)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 451, 101))
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 20, 35, 10))
        self.label.setObjectName("label")
        self.label_18 = QtWidgets.QLabel(self.groupBox)
        self.label_18.setGeometry(QtCore.QRect(200, 20, 35, 10))
        self.label_18.setObjectName("label_18")
        self.label_17 = QtWidgets.QLabel(self.groupBox)
        self.label_17.setGeometry(QtCore.QRect(260, 20, 35, 10))
        self.label_17.setObjectName("label_17")
        self.label_16 = QtWidgets.QLabel(self.groupBox)
        self.label_16.setGeometry(QtCore.QRect(140, 50, 61, 31))
        self.label_16.setObjectName("label_16")
        self.label_13 = QtWidgets.QLabel(self.groupBox)
        self.label_13.setGeometry(QtCore.QRect(10, 60, 35, 10))
        self.label_13.setObjectName("label_13")
        self.label_15 = QtWidgets.QLabel(self.groupBox)
        self.label_15.setGeometry(QtCore.QRect(220, 60, 35, 10))
        self.label_15.setObjectName("label_15")
        self.label_20 = QtWidgets.QLabel(self.groupBox)
        self.label_20.setGeometry(QtCore.QRect(140, 20, 35, 10))
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.groupBox)
        self.label_21.setGeometry(QtCore.QRect(310, 50, 41, 31))
        self.label_21.setObjectName("label_21")
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        self.label_12.setGeometry(QtCore.QRect(370, 50, 51, 31))
        self.label_12.setObjectName("label_12")
        self.label_14 = QtWidgets.QLabel(self.groupBox)
        self.label_14.setGeometry(QtCore.QRect(360, 20, 35, 10))
        self.label_14.setObjectName("label_14")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setGeometry(QtCore.QRect(10, 30, 101, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_2.setGeometry(QtCore.QRect(140, 30, 31, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_3.setGeometry(QtCore.QRect(200, 30, 31, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_4.setGeometry(QtCore.QRect(260, 30, 71, 20))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_5.setGeometry(QtCore.QRect(10, 70, 101, 20))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_6.setGeometry(QtCore.QRect(140, 70, 51, 20))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_7.setGeometry(QtCore.QRect(360, 30, 71, 20))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_8.setGeometry(QtCore.QRect(220, 70, 61, 20))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_9.setGeometry(QtCore.QRect(310, 70, 31, 20))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_10.setGeometry(QtCore.QRect(370, 70, 51, 20))
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 120, 451, 61))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_28 = QtWidgets.QLabel(self.groupBox_2)
        self.label_28.setGeometry(QtCore.QRect(380, 140, 35, 10))
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.groupBox_2)
        self.label_29.setGeometry(QtCore.QRect(320, 150, 51, 16))
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.groupBox_2)
        self.label_30.setGeometry(QtCore.QRect(180, 140, 35, 10))
        self.label_30.setObjectName("label_30")
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        self.label_11.setGeometry(QtCore.QRect(310, 15, 61, 21))
        self.label_11.setObjectName("label_11")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(140, 10, 61, 31))
        self.label_8.setObjectName("label_8")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 51, 31))
        self.label_2.setObjectName("label_2")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_11.setGeometry(QtCore.QRect(10, 30, 101, 20))
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_12.setGeometry(QtCore.QRect(140, 30, 51, 20))
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setGeometry(QtCore.QRect(220, 15, 61, 21))
        self.label_10.setObjectName("label_10")
        self.lineEdit_13 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_13.setGeometry(QtCore.QRect(220, 30, 61, 20))
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.lineEdit_14 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_14.setGeometry(QtCore.QRect(310, 30, 61, 20))
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 190, 451, 121))
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_31 = QtWidgets.QLabel(self.groupBox_3)
        self.label_31.setGeometry(QtCore.QRect(380, 140, 35, 10))
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(self.groupBox_3)
        self.label_32.setGeometry(QtCore.QRect(320, 150, 51, 16))
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(self.groupBox_3)
        self.label_33.setGeometry(QtCore.QRect(180, 140, 35, 10))
        self.label_33.setObjectName("label_33")
        self.lineEdit_15 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_15.setGeometry(QtCore.QRect(10, 30, 71, 20))
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.lineEdit_17 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_17.setGeometry(QtCore.QRect(220, 30, 91, 20))
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setGeometry(QtCore.QRect(10, 20, 35, 10))
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setGeometry(QtCore.QRect(110, 10, 51, 31))
        self.label_5.setObjectName("label_5")
        self.lineEdit_16 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_16.setGeometry(QtCore.QRect(110, 30, 71, 20))
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setGeometry(QtCore.QRect(220, 16, 41, 20))
        self.label_6.setObjectName("label_6")
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        self.label_9.setGeometry(QtCore.QRect(10, 60, 35, 10))
        self.label_9.setObjectName("label_9")
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setGeometry(QtCore.QRect(340, 16, 41, 20))
        self.label_4.setObjectName("label_4")
        self.lineEdit_19 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_19.setGeometry(QtCore.QRect(340, 30, 91, 20))
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.groupBox_3)
        self.plainTextEdit.setGeometry(QtCore.QRect(10, 70, 421, 41))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 320, 451, 231))
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_7 = QtWidgets.QLabel(self.groupBox_4)
        self.label_7.setGeometry(QtCore.QRect(10, 10, 71, 31))
        self.label_7.setObjectName("label_7")
        self.tableWidget = QtWidgets.QTableWidget(self.groupBox_4)
        self.tableWidget.setGeometry(QtCore.QRect(10, 30, 421, 101))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.label_19 = QtWidgets.QLabel(self.groupBox_4)
        self.label_19.setGeometry(QtCore.QRect(10, 130, 71, 31))
        self.label_19.setObjectName("label_19")
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setGeometry(QtCore.QRect(470, 120, 171, 91))
        self.groupBox_5.setObjectName("groupBox_5")
        self.label_22 = QtWidgets.QLabel(self.groupBox_5)
        self.label_22.setGeometry(QtCore.QRect(10, 20, 35, 10))
        self.label_22.setObjectName("label_22")
        self.lineEdit_18 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_18.setGeometry(QtCore.QRect(10, 30, 101, 20))
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.pushButton = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton.setGeometry(QtCore.QRect(10, 60, 56, 17))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 653, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Patient Information"))
        self.label.setText(_translate("MainWindow", "Patient ID"))
        self.label_18.setText(_translate("MainWindow", "Gender"))
        self.label_17.setText(_translate("MainWindow", "Ethnicity"))
        self.label_16.setText(_translate("MainWindow", "Marital Status"))
        self.label_13.setText(_translate("MainWindow", "Insurance"))
        self.label_15.setText(_translate("MainWindow", "Religion"))
        self.label_20.setText(_translate("MainWindow", "Age"))
        self.label_21.setText(_translate("MainWindow", "Death Age"))
        self.label_12.setText(_translate("MainWindow", "Death Time"))
        self.label_14.setText(_translate("MainWindow", "Language"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Admission Information"))
        self.label_28.setText(_translate("MainWindow", "Ethnicity"))
        self.label_29.setText(_translate("MainWindow", "Marital Status"))
        self.label_30.setText(_translate("MainWindow", "Insurance"))
        self.label_11.setText(_translate("MainWindow", "Discharge Time"))
        self.label_8.setText(_translate("MainWindow", "Admission Type"))
        self.label_2.setText(_translate("MainWindow", "Admission ID"))
        self.label_10.setText(_translate("MainWindow", "Admission Time"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Diagnosis"))
        self.label_31.setText(_translate("MainWindow", "Ethnicity"))
        self.label_32.setText(_translate("MainWindow", "Marital Status"))
        self.label_33.setText(_translate("MainWindow", "Insurance"))
        self.label_3.setText(_translate("MainWindow", "Code"))
        self.label_5.setText(_translate("MainWindow", "ICD9 Code"))
        self.label_6.setText(_translate("MainWindow", "Title"))
        self.label_9.setText(_translate("MainWindow", "Diagnosis"))
        self.label_4.setText(_translate("MainWindow", "Descriptor"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Antimicrobial Resistance"))
        self.label_7.setText(_translate("MainWindow", "Antimicrobial Table"))
        self.label_19.setText(_translate("MainWindow", "Graphs"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Health Record Input"))
        self.label_22.setText(_translate("MainWindow", "Patient ID"))
        self.pushButton.setText(_translate("MainWindow", "Search"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

