# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QtUI_rev.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(617, 684)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 90, 291, 241))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setAcceptDrops(True)
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_29 = QtWidgets.QLabel(self.groupBox_2)
        self.label_29.setGeometry(QtCore.QRect(10, 146, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(10, 26, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_20 = QtWidgets.QLabel(self.groupBox_2)
        self.label_20.setGeometry(QtCore.QRect(10, 50, 35, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.label_18 = QtWidgets.QLabel(self.groupBox_2)
        self.label_18.setGeometry(QtCore.QRect(10, 100, 35, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.label_17 = QtWidgets.QLabel(self.groupBox_2)
        self.label_17.setGeometry(QtCore.QRect(10, 115, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.label_14 = QtWidgets.QLabel(self.groupBox_2)
        self.label_14.setGeometry(QtCore.QRect(10, 130, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.groupBox_2)
        self.label_15.setGeometry(QtCore.QRect(10, 160, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.label_13 = QtWidgets.QLabel(self.groupBox_2)
        self.label_13.setGeometry(QtCore.QRect(10, 175, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_21 = QtWidgets.QLabel(self.groupBox_2)
        self.label_21.setGeometry(QtCore.QRect(30, 80, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.label_19 = QtWidgets.QLabel(self.groupBox_2)
        self.label_19.setGeometry(QtCore.QRect(10, 70, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.subject_id = QtWidgets.QLabel(self.groupBox_2)
        self.subject_id.setGeometry(QtCore.QRect(110, 26, 161, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.subject_id.setFont(font)
        self.subject_id.setObjectName("subject_id")
        self.hadm_id = QtWidgets.QLabel(self.groupBox_2)
        self.hadm_id.setGeometry(QtCore.QRect(110, 40, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.hadm_id.setFont(font)
        self.hadm_id.setObjectName("hadm_id")
        self.age = QtWidgets.QLabel(self.groupBox_2)
        self.age.setGeometry(QtCore.QRect(110, 50, 35, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.age.setFont(font)
        self.age.setObjectName("age")
        self.expire_flag = QtWidgets.QLabel(self.groupBox_2)
        self.expire_flag.setGeometry(QtCore.QRect(110, 70, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.expire_flag.setFont(font)
        self.expire_flag.setObjectName("expire_flag")
        self.age_death = QtWidgets.QLabel(self.groupBox_2)
        self.age_death.setGeometry(QtCore.QRect(110, 80, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.age_death.setFont(font)
        self.age_death.setObjectName("age_death")
        self.gender = QtWidgets.QLabel(self.groupBox_2)
        self.gender.setGeometry(QtCore.QRect(110, 100, 35, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.gender.setFont(font)
        self.gender.setObjectName("gender")
        self.ethnicity = QtWidgets.QLabel(self.groupBox_2)
        self.ethnicity.setGeometry(QtCore.QRect(110, 110, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ethnicity.setFont(font)
        self.ethnicity.setObjectName("ethnicity")
        self.language = QtWidgets.QLabel(self.groupBox_2)
        self.language.setGeometry(QtCore.QRect(110, 130, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.language.setFont(font)
        self.language.setObjectName("language")
        self.marital_status = QtWidgets.QLabel(self.groupBox_2)
        self.marital_status.setGeometry(QtCore.QRect(110, 139, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.marital_status.setFont(font)
        self.marital_status.setObjectName("marital_status")
        self.religion = QtWidgets.QLabel(self.groupBox_2)
        self.religion.setGeometry(QtCore.QRect(110, 160, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.religion.setFont(font)
        self.religion.setObjectName("religion")
        self.insurance = QtWidgets.QLabel(self.groupBox_2)
        self.insurance.setGeometry(QtCore.QRect(110, 170, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.insurance.setFont(font)
        self.insurance.setObjectName("insurance")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(180, 20, 291, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_23.setFont(font)
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setWordWrap(False)
        self.label_23.setObjectName("label_23")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(310, 90, 291, 131))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setAcceptDrops(True)
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_22 = QtWidgets.QLabel(self.groupBox_4)
        self.label_22.setGeometry(QtCore.QRect(30, 40, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.label_56 = QtWidgets.QLabel(self.groupBox_4)
        self.label_56.setGeometry(QtCore.QRect(10, 26, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_56.setFont(font)
        self.label_56.setObjectName("label_56")
        self.label_57 = QtWidgets.QLabel(self.groupBox_4)
        self.label_57.setGeometry(QtCore.QRect(10, 50, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_57.setFont(font)
        self.label_57.setObjectName("label_57")
        self.label_58 = QtWidgets.QLabel(self.groupBox_4)
        self.label_58.setGeometry(QtCore.QRect(10, 100, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_58.setFont(font)
        self.label_58.setObjectName("label_58")
        self.label_63 = QtWidgets.QLabel(self.groupBox_4)
        self.label_63.setGeometry(QtCore.QRect(10, 80, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_63.setFont(font)
        self.label_63.setObjectName("label_63")
        self.label_64 = QtWidgets.QLabel(self.groupBox_4)
        self.label_64.setGeometry(QtCore.QRect(10, 70, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_64.setFont(font)
        self.label_64.setObjectName("label_64")
        self.subject_id_5 = QtWidgets.QLabel(self.groupBox_4)
        self.subject_id_5.setGeometry(QtCore.QRect(140, 26, 141, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.subject_id_5.setFont(font)
        self.subject_id_5.setObjectName("subject_id_5")
        self.hadm_id_5 = QtWidgets.QLabel(self.groupBox_4)
        self.hadm_id_5.setGeometry(QtCore.QRect(140, 40, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.hadm_id_5.setFont(font)
        self.hadm_id_5.setObjectName("hadm_id_5")
        self.age_5 = QtWidgets.QLabel(self.groupBox_4)
        self.age_5.setGeometry(QtCore.QRect(140, 50, 35, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.age_5.setFont(font)
        self.age_5.setObjectName("age_5")
        self.expire_flag_5 = QtWidgets.QLabel(self.groupBox_4)
        self.expire_flag_5.setGeometry(QtCore.QRect(140, 70, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.expire_flag_5.setFont(font)
        self.expire_flag_5.setObjectName("expire_flag_5")
        self.age_death_5 = QtWidgets.QLabel(self.groupBox_4)
        self.age_death_5.setGeometry(QtCore.QRect(140, 80, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.age_death_5.setFont(font)
        self.age_death_5.setObjectName("age_death_5")
        self.gender_5 = QtWidgets.QLabel(self.groupBox_4)
        self.gender_5.setGeometry(QtCore.QRect(140, 100, 35, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.gender_5.setFont(font)
        self.gender_5.setObjectName("gender_5")
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setGeometry(QtCore.QRect(310, 230, 291, 101))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setAcceptDrops(True)
        self.groupBox_5.setObjectName("groupBox_5")
        self.label_67 = QtWidgets.QLabel(self.groupBox_5)
        self.label_67.setGeometry(QtCore.QRect(10, 26, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_67.setFont(font)
        self.label_67.setObjectName("label_67")
        self.subject_id_7 = QtWidgets.QLabel(self.groupBox_5)
        self.subject_id_7.setGeometry(QtCore.QRect(80, 26, 141, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.subject_id_7.setFont(font)
        self.subject_id_7.setObjectName("subject_id_7")
        self.textBrowser = QtWidgets.QTextBrowser(self.groupBox_5)
        self.textBrowser.setGeometry(QtCore.QRect(90, 30, 191, 61))
        self.textBrowser.setObjectName("textBrowser")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 340, 591, 291))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setAcceptDrops(True)
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_31 = QtWidgets.QLabel(self.groupBox_3)
        self.label_31.setGeometry(QtCore.QRect(20, 146, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.label_33 = QtWidgets.QLabel(self.groupBox_3)
        self.label_33.setGeometry(QtCore.QRect(10, 100, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.label_62 = QtWidgets.QLabel(self.groupBox_3)
        self.label_62.setGeometry(QtCore.QRect(20, 115, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_62.setFont(font)
        self.label_62.setObjectName("label_62")
        self.label_68 = QtWidgets.QLabel(self.groupBox_3)
        self.label_68.setGeometry(QtCore.QRect(20, 130, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_68.setFont(font)
        self.label_68.setObjectName("label_68")
        self.label_69 = QtWidgets.QLabel(self.groupBox_3)
        self.label_69.setGeometry(QtCore.QRect(20, 160, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_69.setFont(font)
        self.label_69.setObjectName("label_69")
        self.label_70 = QtWidgets.QLabel(self.groupBox_3)
        self.label_70.setGeometry(QtCore.QRect(20, 175, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_70.setFont(font)
        self.label_70.setObjectName("label_70")
        self.tableWidget = QtWidgets.QTableWidget(self.groupBox_3)
        self.tableWidget.setGeometry(QtCore.QRect(10, 20, 571, 71))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.label_71 = QtWidgets.QLabel(self.groupBox_3)
        self.label_71.setGeometry(QtCore.QRect(20, 190, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_71.setFont(font)
        self.label_71.setObjectName("label_71")
        self.label_72 = QtWidgets.QLabel(self.groupBox_3)
        self.label_72.setGeometry(QtCore.QRect(20, 200, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_72.setFont(font)
        self.label_72.setObjectName("label_72")
        self.label_73 = QtWidgets.QLabel(self.groupBox_3)
        self.label_73.setGeometry(QtCore.QRect(20, 220, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_73.setFont(font)
        self.label_73.setObjectName("label_73")
        self.label_74 = QtWidgets.QLabel(self.groupBox_3)
        self.label_74.setGeometry(QtCore.QRect(20, 230, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_74.setFont(font)
        self.label_74.setObjectName("label_74")
        self.label_75 = QtWidgets.QLabel(self.groupBox_3)
        self.label_75.setGeometry(QtCore.QRect(20, 250, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_75.setFont(font)
        self.label_75.setObjectName("label_75")
        self.label_76 = QtWidgets.QLabel(self.groupBox_3)
        self.label_76.setGeometry(QtCore.QRect(20, 260, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_76.setFont(font)
        self.label_76.setObjectName("label_76")
        self.label_77 = QtWidgets.QLabel(self.groupBox_3)
        self.label_77.setGeometry(QtCore.QRect(230, 260, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_77.setFont(font)
        self.label_77.setObjectName("label_77")
        self.label_32 = QtWidgets.QLabel(self.groupBox_3)
        self.label_32.setGeometry(QtCore.QRect(230, 146, 161, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.label_78 = QtWidgets.QLabel(self.groupBox_3)
        self.label_78.setGeometry(QtCore.QRect(230, 230, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_78.setFont(font)
        self.label_78.setObjectName("label_78")
        self.label_79 = QtWidgets.QLabel(self.groupBox_3)
        self.label_79.setGeometry(QtCore.QRect(230, 160, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_79.setFont(font)
        self.label_79.setObjectName("label_79")
        self.label_80 = QtWidgets.QLabel(self.groupBox_3)
        self.label_80.setGeometry(QtCore.QRect(230, 175, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_80.setFont(font)
        self.label_80.setObjectName("label_80")
        self.label_81 = QtWidgets.QLabel(self.groupBox_3)
        self.label_81.setGeometry(QtCore.QRect(230, 115, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_81.setFont(font)
        self.label_81.setObjectName("label_81")
        self.label_82 = QtWidgets.QLabel(self.groupBox_3)
        self.label_82.setGeometry(QtCore.QRect(230, 220, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_82.setFont(font)
        self.label_82.setObjectName("label_82")
        self.label_83 = QtWidgets.QLabel(self.groupBox_3)
        self.label_83.setGeometry(QtCore.QRect(230, 130, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_83.setFont(font)
        self.label_83.setObjectName("label_83")
        self.label_84 = QtWidgets.QLabel(self.groupBox_3)
        self.label_84.setGeometry(QtCore.QRect(230, 200, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_84.setFont(font)
        self.label_84.setObjectName("label_84")
        self.label_85 = QtWidgets.QLabel(self.groupBox_3)
        self.label_85.setGeometry(QtCore.QRect(230, 190, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_85.setFont(font)
        self.label_85.setObjectName("label_85")
        self.label_86 = QtWidgets.QLabel(self.groupBox_3)
        self.label_86.setGeometry(QtCore.QRect(230, 250, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_86.setFont(font)
        self.label_86.setObjectName("label_86")
        self.label_87 = QtWidgets.QLabel(self.groupBox_3)
        self.label_87.setGeometry(QtCore.QRect(440, 160, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_87.setFont(font)
        self.label_87.setObjectName("label_87")
        self.label_88 = QtWidgets.QLabel(self.groupBox_3)
        self.label_88.setGeometry(QtCore.QRect(440, 146, 161, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_88.setFont(font)
        self.label_88.setObjectName("label_88")
        self.label_89 = QtWidgets.QLabel(self.groupBox_3)
        self.label_89.setGeometry(QtCore.QRect(440, 115, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_89.setFont(font)
        self.label_89.setObjectName("label_89")
        self.label_90 = QtWidgets.QLabel(self.groupBox_3)
        self.label_90.setGeometry(QtCore.QRect(440, 175, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_90.setFont(font)
        self.label_90.setObjectName("label_90")
        self.label_91 = QtWidgets.QLabel(self.groupBox_3)
        self.label_91.setGeometry(QtCore.QRect(440, 200, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_91.setFont(font)
        self.label_91.setObjectName("label_91")
        self.label_92 = QtWidgets.QLabel(self.groupBox_3)
        self.label_92.setGeometry(QtCore.QRect(440, 220, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_92.setFont(font)
        self.label_92.setObjectName("label_92")
        self.label_93 = QtWidgets.QLabel(self.groupBox_3)
        self.label_93.setGeometry(QtCore.QRect(440, 190, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_93.setFont(font)
        self.label_93.setObjectName("label_93")
        self.label_94 = QtWidgets.QLabel(self.groupBox_3)
        self.label_94.setGeometry(QtCore.QRect(440, 230, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_94.setFont(font)
        self.label_94.setObjectName("label_94")
        self.label_95 = QtWidgets.QLabel(self.groupBox_3)
        self.label_95.setGeometry(QtCore.QRect(440, 130, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_95.setFont(font)
        self.label_95.setObjectName("label_95")
        self.label_97 = QtWidgets.QLabel(self.groupBox_3)
        self.label_97.setGeometry(QtCore.QRect(440, 250, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_97.setFont(font)
        self.label_97.setObjectName("label_97")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 617, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Patient Information"))
        self.label_29.setText(_translate("MainWindow", "Marital Status"))
        self.label_2.setText(_translate("MainWindow", "Hospital Visit ID"))
        self.label.setText(_translate("MainWindow", "Patient ID"))
        self.label_20.setText(_translate("MainWindow", "Age"))
        self.label_18.setText(_translate("MainWindow", "Gender"))
        self.label_17.setText(_translate("MainWindow", "Ethnicity"))
        self.label_14.setText(_translate("MainWindow", "Primary Language"))
        self.label_15.setText(_translate("MainWindow", "Religion"))
        self.label_13.setText(_translate("MainWindow", "Insurance"))
        self.label_21.setText(_translate("MainWindow", "Age of Death"))
        self.label_19.setText(_translate("MainWindow", "Deceased"))
        self.subject_id.setText(_translate("MainWindow", ": "))
        self.hadm_id.setText(_translate("MainWindow", ":"))
        self.age.setText(_translate("MainWindow", ":"))
        self.expire_flag.setText(_translate("MainWindow", ":"))
        self.age_death.setText(_translate("MainWindow", ":"))
        self.gender.setText(_translate("MainWindow", ":"))
        self.ethnicity.setText(_translate("MainWindow", ":"))
        self.language.setText(_translate("MainWindow", ":"))
        self.marital_status.setText(_translate("MainWindow", ":"))
        self.religion.setText(_translate("MainWindow", ":"))
        self.insurance.setText(_translate("MainWindow", ":"))
        self.label_23.setText(_translate("MainWindow", "PATIENT CASE REPORT FORM"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Disease Information"))
        self.label_22.setText(_translate("MainWindow", "Descriptor"))
        self.label_56.setText(_translate("MainWindow", "Condition Diagnosis Code"))
        self.label_57.setText(_translate("MainWindow", "All Diagnoses"))
        self.label_58.setText(_translate("MainWindow", "Discharge Date"))
        self.label_63.setText(_translate("MainWindow", "Admission Date"))
        self.label_64.setText(_translate("MainWindow", "Hospital Admission Type"))
        self.subject_id_5.setText(_translate("MainWindow", ": "))
        self.hadm_id_5.setText(_translate("MainWindow", ":"))
        self.age_5.setText(_translate("MainWindow", ":"))
        self.expire_flag_5.setText(_translate("MainWindow", ":"))
        self.age_death_5.setText(_translate("MainWindow", ":"))
        self.gender_5.setText(_translate("MainWindow", ":"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Prescription Information"))
        self.label_67.setText(_translate("MainWindow", "Medication"))
        self.subject_id_7.setText(_translate("MainWindow", ": "))
        self.groupBox_3.setTitle(_translate("MainWindow", "NARMS Data"))
        self.label_31.setText(_translate("MainWindow", "ATM Aztreonam"))
        self.label_33.setText(_translate("MainWindow", "Dictionary"))
        self.label_62.setText(_translate("MainWindow", "AMI Amikacin"))
        self.label_68.setText(_translate("MainWindow", "AMP Ampicillin"))
        self.label_69.setText(_translate("MainWindow", "AUG Amoxicillin-clavulanic acid"))
        self.label_70.setText(_translate("MainWindow", "AXO Ceftriaxone"))
        self.label_71.setText(_translate("MainWindow", "AZM Azithromycin"))
        self.label_72.setText(_translate("MainWindow", "CAZ Ceftazidime"))
        self.label_73.setText(_translate("MainWindow", "CCV Ceftazidime-clavulanic acid"))
        self.label_74.setText(_translate("MainWindow", "CEP Cephalothin"))
        self.label_75.setText(_translate("MainWindow", "CEQ Cefquinome"))
        self.label_76.setText(_translate("MainWindow", "CHL Chloramphenicol"))
        self.label_77.setText(_translate("MainWindow", "GEN Gentamicin"))
        self.label_32.setText(_translate("MainWindow", "COT Trimethoprim-sulfamethoxazole"))
        self.label_78.setText(_translate("MainWindow", "FIS Sulfisoxazole"))
        self.label_79.setText(_translate("MainWindow", "CTC Cefotaxime-clavulanic acid"))
        self.label_80.setText(_translate("MainWindow", "CTX Cefotaxime"))
        self.label_81.setText(_translate("MainWindow", "CIP Ciprofloxacin"))
        self.label_82.setText(_translate("MainWindow", "FFN Florfenicol"))
        self.label_83.setText(_translate("MainWindow", "CLI Clindamycin"))
        self.label_84.setText(_translate("MainWindow", "FEP Cefepime"))
        self.label_85.setText(_translate("MainWindow", "ERY Erythromycin"))
        self.label_86.setText(_translate("MainWindow", "FOX Cefoxitin"))
        self.label_87.setText(_translate("MainWindow", "NAL Naladixic acid"))
        self.label_88.setText(_translate("MainWindow", "MER Meropenem"))
        self.label_89.setText(_translate("MainWindow", "IMI Imipenem"))
        self.label_90.setText(_translate("MainWindow", "PTZ Piperacillin-tazobactam"))
        self.label_91.setText(_translate("MainWindow", "STR Streptomycin"))
        self.label_92.setText(_translate("MainWindow", "TEL Telithromycin"))
        self.label_93.setText(_translate("MainWindow", "SMX Sulfamethoxazole"))
        self.label_94.setText(_translate("MainWindow", "TET Tetracycline"))
        self.label_95.setText(_translate("MainWindow", "KAN Kanamycin"))
        self.label_97.setText(_translate("MainWindow", "TIO Ceftiofur"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

