"""
Form implementation generated from reading ui file 'QtUI_rev3.ui'
Created by: PyQt5 UI code generator 5.11.3
Converted to .py by EHR Team for eCRx project
"""

from collections import OrderedDict
from PyQt5 import QtCore, QtGui, QtWidgets
import pandas as pd
import query as qu
import database_build

class UiOutput1Window(object):
    """Creates output window"""
    def __init__(self, output_window, patient_id, birth_year):
        self.centralwidget = QtWidgets.QWidget(output_window)
        self.group_box_patientinfo = QtWidgets.QGroupBox(self.centralwidget)
        self.label_marital = QtWidgets.QLabel(self.group_box_patientinfo)
        self.label_hospitalid = QtWidgets.QLabel(self.group_box_patientinfo)
        self.label_patientid = QtWidgets.QLabel(self.group_box_patientinfo)
        self.label_age = QtWidgets.QLabel(self.group_box_patientinfo)
        self.label_gender = QtWidgets.QLabel(self.group_box_patientinfo)
        self.label_ethnic = QtWidgets.QLabel(self.group_box_patientinfo)
        self.label_language = QtWidgets.QLabel(self.group_box_patientinfo)
        self.label_religion = QtWidgets.QLabel(self.group_box_patientinfo)
        self.label_insurance = QtWidgets.QLabel(self.group_box_patientinfo)
        self.label_deathage = QtWidgets.QLabel(self.group_box_patientinfo)
        self.label_deceased = QtWidgets.QLabel(self.group_box_patientinfo)
        self.subject_id = QtWidgets.QLabel(self.group_box_patientinfo)
        self.hadm_id = QtWidgets.QLabel(self.group_box_patientinfo)
        self.age = QtWidgets.QLabel(self.group_box_patientinfo)
        self.expire_flag = QtWidgets.QLabel(self.group_box_patientinfo)
        self.age_death = QtWidgets.QLabel(self.group_box_patientinfo)
        self.gender = QtWidgets.QLabel(self.group_box_patientinfo)
        self.ethnicity = QtWidgets.QLabel(self.group_box_patientinfo)
        self.language = QtWidgets.QLabel(self.group_box_patientinfo)
        self.marital_status = QtWidgets.QLabel(self.group_box_patientinfo)
        self.religion = QtWidgets.QLabel(self.group_box_patientinfo)
        self.insurance = QtWidgets.QLabel(self.group_box_patientinfo)
        self.label_title = QtWidgets.QLabel(self.centralwidget)
        self.group_box_diseaseinfo = QtWidgets.QGroupBox(self.centralwidget)
        self.label_descriptor = QtWidgets.QLabel(self.group_box_diseaseinfo)
        self.label_diagnosiscode = QtWidgets.QLabel(self.group_box_diseaseinfo)
        self.label_alldiagnoses = QtWidgets.QLabel(self.group_box_diseaseinfo)
        self.label_dischargedate = QtWidgets.QLabel(self.group_box_diseaseinfo)
        self.label_admissiondate = QtWidgets.QLabel(self.group_box_diseaseinfo)
        self.label_admissiontype = QtWidgets.QLabel(self.group_box_diseaseinfo)
        self.code = QtWidgets.QLabel(self.group_box_diseaseinfo)
        self.descriptor = QtWidgets.QLabel(self.group_box_diseaseinfo)
        self.long_title = QtWidgets.QLabel(self.group_box_diseaseinfo)
        self.admission_type = QtWidgets.QLabel(self.group_box_diseaseinfo)
        self.admit_new = QtWidgets.QLabel(self.group_box_diseaseinfo)
        self.disch_new = QtWidgets.QLabel(self.group_box_diseaseinfo)
        self.group_box_prescriptioninfo = QtWidgets.QGroupBox(self.centralwidget)
        self.label_medication = QtWidgets.QLabel(self.group_box_prescriptioninfo)
        self.label_doublecolon = QtWidgets.QLabel(self.group_box_prescriptioninfo)
        self.text_browser = QtWidgets.QTextBrowser(self.group_box_prescriptioninfo)
        self.group_box_narmsdata = QtWidgets.QGroupBox(self.centralwidget)
        self.label_atm = QtWidgets.QLabel(self.group_box_narmsdata)
        self.label_dictionary = QtWidgets.QLabel(self.group_box_narmsdata)
        self.label_ami = QtWidgets.QLabel(self.group_box_narmsdata)
        self.label_amp = QtWidgets.QLabel(self.group_box_narmsdata)
        self.label_aug = QtWidgets.QLabel(self.group_box_narmsdata)
        self.label_axo = QtWidgets.QLabel(self.group_box_narmsdata)
        self.table_widget = QtWidgets.QTableWidget(self.group_box_narmsdata)
        self.label_azm = QtWidgets.QLabel(self.group_box_narmsdata)
        self.label_caz = QtWidgets.QLabel(self.group_box_narmsdata)
        self.label_ccv = QtWidgets.QLabel(self.group_box_narmsdata)
        self.label_cep = QtWidgets.QLabel(self.group_box_narmsdata)
        self.label_ceq = QtWidgets.QLabel(self.group_box_narmsdata)
        self.label_chl = QtWidgets.QLabel(self.group_box_narmsdata)
        self.label_gen = QtWidgets.QLabel(self.group_box_narmsdata)
        self.label_cot = QtWidgets.QLabel(self.group_box_narmsdata)
        self.label_fis = QtWidgets.QLabel(self.group_box_narmsdata)
        self.label_ctc = QtWidgets.QLabel(self.group_box_narmsdata)
        self.label_ctx = QtWidgets.QLabel(self.group_box_narmsdata)
        self.label_cip = QtWidgets.QLabel(self.group_box_narmsdata)
        self.label_ffn = QtWidgets.QLabel(self.group_box_narmsdata)
        self.label_cli = QtWidgets.QLabel(self.group_box_narmsdata)
        self.label_fep = QtWidgets.QLabel(self.group_box_narmsdata)
        self.label_ery = QtWidgets.QLabel(self.group_box_narmsdata)
        self.label_fox = QtWidgets.QLabel(self.group_box_narmsdata)
        self.label_nal = QtWidgets.QLabel(self.group_box_narmsdata)
        self.label_mer = QtWidgets.QLabel(self.group_box_narmsdata)
        self.label_imi = QtWidgets.QLabel(self.group_box_narmsdata)
        self.label_ptz = QtWidgets.QLabel(self.group_box_narmsdata)
        self.label_str = QtWidgets.QLabel(self.group_box_narmsdata)
        self.label_tel = QtWidgets.QLabel(self.group_box_narmsdata)
        self.label_smx = QtWidgets.QLabel(self.group_box_narmsdata)
        self.label_tet = QtWidgets.QLabel(self.group_box_narmsdata)
        self.label_kan = QtWidgets.QLabel(self.group_box_narmsdata)
        self.label_tio = QtWidgets.QLabel(self.group_box_narmsdata)
        self.menubar = QtWidgets.QMenuBar(output_window)
        self.statusbar = QtWidgets.QStatusBar(output_window)

        self.setup_ui(output_window, patient_id, birth_year)

    def load_data(self, data):
        """Printing narms data to column in the UI"""
        i = 0
        for key in data.keys():
            key = QtWidgets.QTableWidgetItem(key)
            key.setTextAlignment(QtCore.Qt.AlignCenter)
            self.table_widget.setHorizontalHeaderItem(i, key)
            i += 1

        i = 0
        for value in data.values():
            value = QtWidgets.QTableWidgetItem(value)
            value.setTextAlignment(QtCore.Qt.AlignCenter)
            self.table_widget.setItem(0, i, value)
            i += 1

    def setup_ui(self, output_window, patient_id, birth_year):
        """sets up the user interface"""
        output_window.setObjectName("output_window")
        output_window.resize(884, 824)
        self.centralwidget.setObjectName("centralwidget")
        self.group_box_patientinfo.setGeometry(QtCore.QRect(10, 90, 421, 241))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.group_box_patientinfo.setFont(font)
        self.group_box_patientinfo.setAcceptDrops(True)
        self.group_box_patientinfo.setObjectName("group_box_patientinfo")
        self.label_marital.setGeometry(QtCore.QRect(10, 146, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_marital.setFont(font)
        self.label_marital.setObjectName("label_marital")
        self.label_hospitalid.setGeometry(QtCore.QRect(10, 40, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_hospitalid.setFont(font)
        self.label_hospitalid.setObjectName("label_hospitalid")
        self.label_patientid.setGeometry(QtCore.QRect(10, 26, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_patientid.setFont(font)
        self.label_patientid.setObjectName("label_patientid")
        self.label_age.setGeometry(QtCore.QRect(10, 50, 35, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_age.setFont(font)
        self.label_age.setObjectName("label_age")
        self.label_gender.setGeometry(QtCore.QRect(10, 100, 35, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_gender.setFont(font)
        self.label_gender.setObjectName("label_gender")
        self.label_ethnic.setGeometry(QtCore.QRect(10, 115, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_ethnic.setFont(font)
        self.label_ethnic.setObjectName("label_ethnic")
        self.label_language.setGeometry(QtCore.QRect(10, 130, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_language.setFont(font)
        self.label_language.setObjectName("label_language")
        self.label_religion.setGeometry(QtCore.QRect(10, 160, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_religion.setFont(font)
        self.label_religion.setObjectName("label_religion")
        self.label_insurance.setGeometry(QtCore.QRect(10, 175, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_insurance.setFont(font)
        self.label_insurance.setObjectName("label_insurance")
        self.label_deathage.setGeometry(QtCore.QRect(30, 80, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_deathage.setFont(font)
        self.label_deathage.setObjectName("label_deathage")
        self.label_deceased.setGeometry(QtCore.QRect(10, 70, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_deceased.setFont(font)
        self.label_deceased.setObjectName("label_deceased")
        self.subject_id.setGeometry(QtCore.QRect(130, 26, 251, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.subject_id.setFont(font)
        self.subject_id.setObjectName("subject_id")
        self.hadm_id.setGeometry(QtCore.QRect(130, 40, 251, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.hadm_id.setFont(font)
        self.hadm_id.setObjectName("hadm_id")
        self.age.setGeometry(QtCore.QRect(130, 50, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.age.setFont(font)
        self.age.setObjectName("age")
        self.expire_flag.setGeometry(QtCore.QRect(130, 70, 251, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.expire_flag.setFont(font)
        self.expire_flag.setObjectName("expire_flag")
        self.age_death.setGeometry(QtCore.QRect(130, 80, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.age_death.setFont(font)
        self.age_death.setObjectName("age_death")
        self.gender.setGeometry(QtCore.QRect(130, 100, 251, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.gender.setFont(font)
        self.gender.setObjectName("gender")
        self.ethnicity.setGeometry(QtCore.QRect(130, 110, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ethnicity.setFont(font)
        self.ethnicity.setObjectName("ethnicity")
        self.language.setGeometry(QtCore.QRect(130, 130, 251, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.language.setFont(font)
        self.language.setObjectName("language")
        self.marital_status.setGeometry(QtCore.QRect(130, 139, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.marital_status.setFont(font)
        self.marital_status.setObjectName("marital_status")
        self.religion.setGeometry(QtCore.QRect(130, 160, 251, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.religion.setFont(font)
        self.religion.setObjectName("religion")
        self.insurance.setGeometry(QtCore.QRect(130, 170, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.insurance.setFont(font)
        self.insurance.setObjectName("insurance")
        self.label_title.setGeometry(QtCore.QRect(20, 20, 841, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_title.setFont(font)
        self.label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title.setWordWrap(False)
        self.label_title.setObjectName("label_title")
        self.group_box_diseaseinfo.setGeometry(QtCore.QRect(450, 90, 411, 131))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.group_box_diseaseinfo.setFont(font)
        self.group_box_diseaseinfo.setAcceptDrops(True)
        self.group_box_diseaseinfo.setObjectName("group_box_diseaseinfo")
        self.label_descriptor.setGeometry(QtCore.QRect(30, 40, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_descriptor.setFont(font)
        self.label_descriptor.setObjectName("label_descriptor")
        self.label_diagnosiscode.setGeometry(QtCore.QRect(10, 26, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_diagnosiscode.setFont(font)
        self.label_diagnosiscode.setObjectName("label_diagnosiscode")
        self.label_alldiagnoses.setGeometry(QtCore.QRect(10, 50, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_alldiagnoses.setFont(font)
        self.label_alldiagnoses.setObjectName("label_alldiagnoses")
        self.label_dischargedate.setGeometry(QtCore.QRect(10, 100, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_dischargedate.setFont(font)
        self.label_dischargedate.setObjectName("label_dischargedate")
        self.label_admissiondate.setGeometry(QtCore.QRect(10, 80, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_admissiondate.setFont(font)
        self.label_admissiondate.setObjectName("label_admissiondate")
        self.label_admissiontype.setGeometry(QtCore.QRect(10, 70, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_admissiontype.setFont(font)
        self.label_admissiontype.setObjectName("label_admissiontype")
        self.code.setGeometry(QtCore.QRect(170, 26, 231, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.code.setFont(font)
        self.code.setObjectName("code")
        self.descriptor.setGeometry(QtCore.QRect(170, 40, 231, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.descriptor.setFont(font)
        self.descriptor.setObjectName("descriptor")
        self.long_title.setGeometry(QtCore.QRect(170, 50, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.long_title.setFont(font)
        self.long_title.setObjectName("long_title")
        self.admission_type.setGeometry(QtCore.QRect(170, 70, 231, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.admission_type.setFont(font)
        self.admission_type.setObjectName("admission_type")
        self.admit_new.setGeometry(QtCore.QRect(170, 80, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.admit_new.setFont(font)
        self.admit_new.setObjectName("admit_new")
        self.disch_new.setGeometry(QtCore.QRect(170, 100, 231, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.disch_new.setFont(font)
        self.disch_new.setObjectName("disch_new")
        self.group_box_prescriptioninfo.setGeometry(QtCore.QRect(450, 230, 411, 101))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.group_box_prescriptioninfo.setFont(font)
        self.group_box_prescriptioninfo.setAcceptDrops(True)
        self.group_box_prescriptioninfo.setObjectName("group_box_prescriptioninfo")
        self.label_medication.setGeometry(QtCore.QRect(10, 26, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_medication.setFont(font)
        self.label_medication.setObjectName("label_medication")
        self.label_doublecolon.setGeometry(QtCore.QRect(80, 26, 141, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_doublecolon.setFont(font)
        self.label_doublecolon.setObjectName("label_doublecolon")
        self.text_browser.setGeometry(QtCore.QRect(90, 30, 311, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.text_browser.setFont(font)
        self.text_browser.setObjectName("text_browser")
        self.group_box_narmsdata.setGeometry(QtCore.QRect(10, 340, 851, 381))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.group_box_narmsdata.setFont(font)
        self.group_box_narmsdata.setAcceptDrops(True)
        self.group_box_narmsdata.setObjectName("group_box_narmsdata")
        self.label_atm.setGeometry(QtCore.QRect(20, 216, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_atm.setFont(font)
        self.label_atm.setObjectName("label_atm")
        self.label_dictionary.setGeometry(QtCore.QRect(10, 170, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_dictionary.setFont(font)
        self.label_dictionary.setObjectName("label_dictionary")
        self.label_ami.setGeometry(QtCore.QRect(20, 185, 291, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_ami.setFont(font)
        self.label_ami.setObjectName("label_ami")
        self.label_amp.setGeometry(QtCore.QRect(20, 200, 291, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_amp.setFont(font)
        self.label_amp.setObjectName("label_amp")
        self.label_aug.setGeometry(QtCore.QRect(20, 230, 291, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_aug.setFont(font)
        self.label_aug.setObjectName("label_aug")
        self.label_axo.setGeometry(QtCore.QRect(20, 245, 291, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_axo.setFont(font)
        self.label_axo.setObjectName("label_axo")
        self.table_widget.setGeometry(QtCore.QRect(10, 30, 831, 121))
        self.table_widget.setObjectName("table_widget")
        self.table_widget.setColumnCount(35)
        self.table_widget.setRowCount(1)
        self.label_azm.setGeometry(QtCore.QRect(20, 260, 291, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_azm.setFont(font)
        self.label_azm.setObjectName("label_azm")
        self.label_caz.setGeometry(QtCore.QRect(20, 270, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_caz.setFont(font)
        self.label_caz.setObjectName("label_caz")
        self.label_ccv.setGeometry(QtCore.QRect(20, 290, 291, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_ccv.setFont(font)
        self.label_ccv.setObjectName("label_ccv")
        self.label_cep.setGeometry(QtCore.QRect(20, 300, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_cep.setFont(font)
        self.label_cep.setObjectName("label_cep")
        self.label_ceq.setGeometry(QtCore.QRect(20, 320, 291, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_ceq.setFont(font)
        self.label_ceq.setObjectName("label_ceq")
        self.label_chl.setGeometry(QtCore.QRect(20, 330, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_chl.setFont(font)
        self.label_chl.setObjectName("label_chl")
        self.label_gen.setGeometry(QtCore.QRect(350, 330, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_gen.setFont(font)
        self.label_gen.setObjectName("label_gen")
        self.label_cot.setGeometry(QtCore.QRect(350, 216, 291, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_cot.setFont(font)
        self.label_cot.setObjectName("label_cot")
        self.label_fis.setGeometry(QtCore.QRect(350, 300, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_fis.setFont(font)
        self.label_fis.setObjectName("label_fis")
        self.label_ctc.setGeometry(QtCore.QRect(350, 230, 291, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_ctc.setFont(font)
        self.label_ctc.setObjectName("label_ctc")
        self.label_ctx.setGeometry(QtCore.QRect(350, 245, 291, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_ctx.setFont(font)
        self.label_ctx.setObjectName("label_ctx")
        self.label_cip.setGeometry(QtCore.QRect(350, 185, 291, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_cip.setFont(font)
        self.label_cip.setObjectName("label_cip")
        self.label_ffn.setGeometry(QtCore.QRect(350, 290, 291, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_ffn.setFont(font)
        self.label_ffn.setObjectName("label_ffn")
        self.label_cli.setGeometry(QtCore.QRect(350, 200, 291, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_cli.setFont(font)
        self.label_cli.setObjectName("label_cli")
        self.label_fep.setGeometry(QtCore.QRect(350, 270, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_fep.setFont(font)
        self.label_fep.setObjectName("label_fep")
        self.label_ery.setGeometry(QtCore.QRect(350, 260, 291, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_ery.setFont(font)
        self.label_ery.setObjectName("label_ery")
        self.label_fox.setGeometry(QtCore.QRect(350, 320, 291, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_fox.setFont(font)
        self.label_fox.setObjectName("label_fox")
        self.label_nal.setGeometry(QtCore.QRect(670, 230, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_nal.setFont(font)
        self.label_nal.setObjectName("label_nal")
        self.label_mer.setGeometry(QtCore.QRect(670, 216, 181, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_mer.setFont(font)
        self.label_mer.setObjectName("label_mer")
        self.label_imi.setGeometry(QtCore.QRect(670, 185, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_imi.setFont(font)
        self.label_imi.setObjectName("label_imi")
        self.label_ptz.setGeometry(QtCore.QRect(670, 245, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_ptz.setFont(font)
        self.label_ptz.setObjectName("label_ptz")
        self.label_str.setGeometry(QtCore.QRect(670, 270, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_str.setFont(font)
        self.label_str.setObjectName("label_str")
        self.label_tel.setGeometry(QtCore.QRect(670, 290, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_tel.setFont(font)
        self.label_tel.setObjectName("label_tel")
        self.label_smx.setGeometry(QtCore.QRect(670, 260, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_smx.setFont(font)
        self.label_smx.setObjectName("label_smx")
        self.label_tet.setGeometry(QtCore.QRect(670, 300, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_tet.setFont(font)
        self.label_tet.setObjectName("label_tet")
        self.label_kan.setGeometry(QtCore.QRect(670, 200, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_kan.setFont(font)
        self.label_kan.setObjectName("label_kan")
        self.label_tio.setGeometry(QtCore.QRect(670, 320, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_tio.setFont(font)
        self.label_tio.setObjectName("label_tio")
        output_window.setCentralWidget(self.centralwidget)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 884, 18))
        self.menubar.setObjectName("menubar")
        output_window.setMenuBar(self.menubar)
        self.statusbar.setObjectName("statusbar")
        output_window.setStatusBar(self.statusbar)

        self.retranslate_ui(output_window)
        QtCore.QMetaObject.connectSlotsByName(output_window)

        self.query_values(patient_id, birth_year)

    def retranslate_ui(self, output_window):
        """retranslates variables"""
        _translate = QtCore.QCoreApplication.translate
        output_window.setWindowTitle(_translate("output_window", "MainWindow"))
        self.group_box_patientinfo.setTitle(_translate("output_window", "Patient Information"))
        self.label_marital.setText(_translate("output_window", "Marital Status"))
        self.label_hospitalid.setText(_translate("output_window", "Hospital Visit ID"))
        self.label_patientid.setText(_translate("output_window", "Patient ID"))
        self.label_age.setText(_translate("output_window", "Age"))
        self.label_gender.setText(_translate("output_window", "Gender"))
        self.label_ethnic.setText(_translate("output_window", "Ethnicity"))
        self.label_language.setText(_translate("output_window", "Primary Language"))
        self.label_religion.setText(_translate("output_window", "Religion"))
        self.label_insurance.setText(_translate("output_window", "Insurance"))
        self.label_deathage.setText(_translate("output_window", "Age of Death"))
        self.label_deceased.setText(_translate("output_window", "Deceased"))
        self.subject_id.setText(_translate("output_window", ": "))
        self.hadm_id.setText(_translate("output_window", ":"))
        self.age.setText(_translate("output_window", ":"))
        self.expire_flag.setText(_translate("output_window", ":"))
        self.age_death.setText(_translate("output_window", ":"))
        self.gender.setText(_translate("output_window", ":"))
        self.ethnicity.setText(_translate("output_window", ":"))
        self.language.setText(_translate("output_window", ":"))
        self.marital_status.setText(_translate("output_window", ":"))
        self.religion.setText(_translate("output_window", ":"))
        self.insurance.setText(_translate("output_window", ":"))
        self.label_title.setText(_translate("output_window", "PATIENT CASE REPORT FORM"))
        self.group_box_diseaseinfo.setTitle(_translate("output_window", "Disease Information"))
        self.label_descriptor.setText(_translate("output_window", "Descriptor"))
        self.label_diagnosiscode.setText(_translate("output_window", "Condition Diagnosis Code"))
        self.label_alldiagnoses.setText(_translate("output_window", "All Diagnoses"))
        self.label_dischargedate.setText(_translate("output_window", "Discharge Date"))
        self.label_admissiondate.setText(_translate("output_window", "Admission Date"))
        self.label_admissiontype.setText(_translate("output_window", "Hospital Admission Type"))
        self.code.setText(_translate("output_window", ": "))
        self.descriptor.setText(_translate("output_window", ":"))
        self.long_title.setText(_translate("output_window", ":"))
        self.admission_type.setText(_translate("output_window", ":"))
        self.admit_new.setText(_translate("output_window", ":"))
        self.disch_new.setText(_translate("output_window", ":"))
        self.group_box_prescriptioninfo.setTitle(_translate("output_window",
                                                            "Prescription Information"))
        self.label_medication.setText(_translate("output_window", "Medication"))
        self.label_doublecolon.setText(_translate("output_window", ": "))
        self.group_box_narmsdata.setTitle(_translate("output_window", "NARMS Data"))
        self.label_atm.setText(_translate("output_window", "ATM Aztreonam"))
        self.label_dictionary.setText(_translate("output_window", "Dictionary"))
        self.label_ami.setText(_translate("output_window", "AMI Amikacin"))
        self.label_amp.setText(_translate("output_window", "AMP Ampicillin"))
        self.label_aug.setText(_translate("output_window", "AUG Amoxicillin-clavulanic acid"))
        self.label_axo.setText(_translate("output_window", "AXO Ceftriaxone"))
        self.label_azm.setText(_translate("output_window", "AZM Azithromycin"))
        self.label_caz.setText(_translate("output_window", "CAZ Ceftazidime"))
        self.label_ccv.setText(_translate("output_window", "CCV Ceftazidime-clavulanic acid"))
        self.label_cep.setText(_translate("output_window", "CEP Cephalothin"))
        self.label_ceq.setText(_translate("output_window", "CEQ Cefquinome"))
        self.label_chl.setText(_translate("output_window", "CHL Chloramphenicol"))
        self.label_gen.setText(_translate("output_window", "GEN Gentamicin"))
        self.label_cot.setText(_translate("output_window", "COT Trimethoprim-sulfamethoxazole"))
        self.label_fis.setText(_translate("output_window", "FIS Sulfisoxazole"))
        self.label_ctc.setText(_translate("output_window", "CTC Cefotaxime-clavulanic acid"))
        self.label_ctx.setText(_translate("output_window", "CTX Cefotaxime"))
        self.label_cip.setText(_translate("output_window", "CIP Ciprofloxacin"))
        self.label_ffn.setText(_translate("output_window", "FFN Florfenicol"))
        self.label_cli.setText(_translate("output_window", "CLI Clindamycin"))
        self.label_fep.setText(_translate("output_window", "FEP Cefepime"))
        self.label_ery.setText(_translate("output_window", "ERY Erythromycin"))
        self.label_fox.setText(_translate("output_window", "FOX Cefoxitin"))
        self.label_nal.setText(_translate("output_window", "NAL Naladixic acid"))
        self.label_mer.setText(_translate("output_window", "MER Meropenem"))
        self.label_imi.setText(_translate("output_window", "IMI Imipenem"))
        self.label_ptz.setText(_translate("output_window", "PTZ Piperacillin-tazobactam"))
        self.label_str.setText(_translate("output_window", "STR Streptomycin"))
        self.label_tel.setText(_translate("output_window", "TEL Telithromycin"))
        self.label_smx.setText(_translate("output_window", "SMX Sulfamethoxazole"))
        self.label_tet.setText(_translate("output_window", "TET Tetracycline"))
        self.label_kan.setText(_translate("output_window", "KAN Kanamycin"))
        self.label_tio.setText(_translate("output_window", "TIO Ceftiofur"))

    def query_values(self, patient_id, birth_year):
        variable, table_narms = self.get_report(patient_id, birth_year)
        self.subject_id.setText(": " + str(variable['subject_id']))
        self.hadm_id.setText(": " + str(variable['hadm_id']))
        self.age.setText(": " + str(variable['age']))
        self.expire_flag.setText(": " + str(variable['expire_flag']))
        self.age_death.setText(": " + str(variable['age_death']))
        self.gender.setText(": " + str(variable['gender']))
        self.ethnicity.setText(": " + str(variable['ethnicity']))
        self.language.setText(": " + str(variable['language']))
        self.marital_status.setText(": " + str(variable['marital_status']))
        self.religion.setText(": " + str(variable['religion']))
        self.insurance.setText(": " + str(variable['insurance']))

        self.code.setText(": " + str(variable['Code']))
        self.descriptor.setText(": " + str(variable['Descriptor']))
        self.long_title.setText(": " + str(variable['long_title']))
        self.admission_type.setText(": " + str(variable['admission_type']))
        self.admit_new.setText(": " + str(variable['admit_new']))
        self.disch_new.setText(": " + str(variable['disch_new']))
        self.text_browser.setText(str(variable['drug']))
        self.load_data(table_narms)

    def get_report(self, subject_id, birth_year):
        '''main report generator program'''
        df1 = database_build.main()
        # df1 = pd.read_csv('../Data/test_file.csv')
        list_tolist = reversed(['hadm_id', 'Code', 'Descriptor', 'icd9_code',
                                'long_title', 'admission_type', 'diagnosis', 'insurance',
                                'language', 'religion', 'marital_status', 'ethnicity',
                                'gender', 'expire_flag', 'age', 'age_death',
                                'age_group', 'admit_year', 'admit_new', 'disch_new', 'description',
                                'drug_type', 'drug', 'formulary_drug_cd'])

        table = qu.query_single(df1, 'subject_id', int(subject_id), ["subject_id"],
                                list_tolist, ["subject_id"])

        ages = table['age'].tolist()
        patient_age = int(ages[0][0])
        year = birth_year + patient_age

        if patient_age <= 4:
            age = '0-4'
        elif patient_age <= 9:
            age = '5-9'
        elif patient_age <= 19:
            age = '10-19'
        elif patient_age <= 29:
            age = '20-29'
        elif patient_age <= 39:
            age = '30-39'
        elif patient_age <= 49:
            age = '40-49'
        elif patient_age <= 59:
            age = '50-59'
        elif patient_age <= 69:
            age = '60-69'
        elif patient_age <= 79:
            age = '70-79'
        elif patient_age >= 80:
            age = '80+'

        for column in list_tolist:
            if column not in list(table.columns.values):
                table[column] = 'Nah'
        narms = qu.narms_query("../Data/narms_processed.csv", year, age)

        data_row = table.iloc[0]
        list_content = (data_row.tolist())

        list_name = ['subject_id', 'hadm_id', 'Code', 'Descriptor', 'icd9_code',
                     'long_title', 'admission_type', 'diagnosis', 'insurance', 'language',
                     'religion', 'marital_status', 'ethnicity', 'gender', 'expire_flag',
                     'age', 'age_death', 'age_group', 'admit_year', 'admit_new',
                     'disch_new', 'description', 'drug_type', 'drug', 'formulary_drug_cd']

        list_narms = ['Data_Year', 'Age_Group', 'Specimen_ID', 'Resistance_Pattern', 'AMI_Concl',
                      'AMP_Concl', 'ATM_Concl', 'AUG_Concl', 'AXO_Concl', 'AZM_Concl', 'CAZ_Concl',
                      'CCV_Concl', 'CEP_Concl', 'CEQ_Concl', 'CHL_Concl', 'CIP_Concl', 'CLI_Concl',
                      'COT_Concl', 'CTC_Concl', 'CTX_Concl', 'ERY_Concl', 'FEP_Concl', 'FFN_Concl',
                      'FIS_Concl', 'FOX_Concl', 'GEN_Concl', 'IMI_Concl', 'KAN_Concl', 'NAL_Concl',
                      'PTZ_Concl', 'SMX_Concl', 'STR_Concl', 'TEL_Concl', 'TET_Concl', 'TIO_Concl']

        variable = {}
        table_narms = OrderedDict()

        for count in range(0, len(list_name)):
            cell = list_content[count]
            if isinstance(cell, list):
                if len(cell) > 1 and list_name[count] != 'drug':
                    list_content[count] = list_content[count][:1]
                elif list_name[count] == 'drug':
                    list_content[count] = list_content[count][:50]
            list_content[count] = str(list_content[count])
            variable[list_name[count]] = list_content[count]

        for count in range(0, len(list_narms)):
            table_narms[list_narms[count]] = str(narms.iloc[0][count])

        for item in variable.keys():
            values_tem = variable[item]
            if (values_tem[0] == '[' and values_tem[1] == "'" and
                    values_tem[len(values_tem) - 2] == "'" and
                    values_tem[len(values_tem) - 1] == ']'):
                variable[item] = values_tem[2:(len(variable[item]) - 2)]
            elif (values_tem[0] == '[' and
                  values_tem[len(values_tem) - 1] == ']'):
                variable[item] = values_tem[1:(len(variable[item]) - 1)]
        variable['drug'] = variable['drug'].replace("'", " ")
        variable['age'] = int(float(variable['age']))
        variable['age'] = str(variable['age'])

        if variable['age_death'] != 'nan':
            variable['age_death'] = int(float(variable['age_death']))
            variable['age_death'] = str(variable['age_death'])
        if variable['expire_flag'] == '1':
            variable['expire_flag'] = 'Death'
        else:
            variable['expire_flag'] = 'Live'

        return variable, table_narms

if __name__ == "__main__":
    import sys
    APP = QtWidgets.QApplication(sys.argv)
    sys.exit(APP.exec_())
