"""
This test file is used to test function in MainWindow.py in EHRTeam
"""
import sys
import unittest
import os.path
from PyQt5 import QtCore, QtGui, QtWidgets
from report_ui import UiOutput1Window
from output_pdf import get_report as pdf_get_report

class TestFunctions(unittest.TestCase):
    """
    Unittest class
    """
    def __init__(self, *args, **kwargs):
        super(TestFunctions, self).__init__(*args, **kwargs)
        self.centralwidget = QtWidgets.QWidget(output_window)
        self.group_box_patientinfo = QtWidgets.QGroupBox(self.centralwidget)
        self.label_marital = QtWidgets.QLabel(self.group_box_patientinfo)
        self.label_hospitalid = QtWidgets.QLabel(self.group_box_patientinfo)
        self.label_patientid = QtWidgets.QLabel(self.group_box_patientinfo)
        self.label_age = QtWidgets.QLabel(self.group_box_patientinfo)
        self.label_gender = QtWidgets.QLabel(self.group_box_patientinfo)
        self.label_ethnic = QtWidgets.QLabel(self.group_box_patientinfo)
        self.label_language = QtWidgets.QLabel(self.group_box_patientinfo)
        self.label_religion = QtWidgets.QLabel(self.group_box_patientinfo)
        self.label_insurance = QtWidgets.QLabel(self.group_box_patientinfo)
        self.label_deathage = QtWidgets.QLabel(self.group_box_patientinfo)
        self.label_deceased = QtWidgets.QLabel(self.group_box_patientinfo)
        self.subject_id = QtWidgets.QLabel(self.group_box_patientinfo)
        self.hadm_id = QtWidgets.QLabel(self.group_box_patientinfo)
        self.age = QtWidgets.QLabel(self.group_box_patientinfo)
        self.expire_flag = QtWidgets.QLabel(self.group_box_patientinfo)
        self.age_death = QtWidgets.QLabel(self.group_box_patientinfo)
        self.gender = QtWidgets.QLabel(self.group_box_patientinfo)
        self.ethnicity = QtWidgets.QLabel(self.group_box_patientinfo)
        self.language = QtWidgets.QLabel(self.group_box_patientinfo)
        self.marital_status = QtWidgets.QLabel(self.group_box_patientinfo)
        self.religion = QtWidgets.QLabel(self.group_box_patientinfo)
        self.insurance = QtWidgets.QLabel(self.group_box_patientinfo)
        self.label_title = QtWidgets.QLabel(self.centralwidget)
        self.group_box_diseaseinfo = QtWidgets.QGroupBox(self.centralwidget)
        self.label_descriptor = QtWidgets.QLabel(self.group_box_diseaseinfo)
        self.label_diagnosiscode = QtWidgets.QLabel(self.group_box_diseaseinfo)
        self.label_alldiagnoses = QtWidgets.QLabel(self.group_box_diseaseinfo)
        self.label_dischargedate = QtWidgets.QLabel(self.group_box_diseaseinfo)
        self.label_admissiondate = QtWidgets.QLabel(self.group_box_diseaseinfo)
        self.label_admissiontype = QtWidgets.QLabel(self.group_box_diseaseinfo)
        self.code = QtWidgets.QLabel(self.group_box_diseaseinfo)
        self.descriptor = QtWidgets.QLabel(self.group_box_diseaseinfo)
        self.long_title = QtWidgets.QLabel(self.group_box_diseaseinfo)
        self.admission_type = QtWidgets.QLabel(self.group_box_diseaseinfo)
        self.admit_new = QtWidgets.QLabel(self.group_box_diseaseinfo)
        self.disch_new = QtWidgets.QLabel(self.group_box_diseaseinfo)
        self.group_box_prescriptioninfo = QtWidgets.QGroupBox(self.centralwidget)
        self.label_medication = QtWidgets.QLabel(self.group_box_prescriptioninfo)
        self.label_doublecolon = QtWidgets.QLabel(self.group_box_prescriptioninfo)
        self.text_browser = QtWidgets.QTextBrowser(self.group_box_prescriptioninfo)
        self.group_box_narmsdata = QtWidgets.QGroupBox(self.centralwidget)
        self.label_atm = QtWidgets.QLabel(self.group_box_narmsdata)
        self.label_dictionary = QtWidgets.QLabel(self.group_box_narmsdata)
        self.label_ami = QtWidgets.QLabel(self.group_box_narmsdata)
        self.label_amp = QtWidgets.QLabel(self.group_box_narmsdata)
        self.label_aug = QtWidgets.QLabel(self.group_box_narmsdata)
        self.label_axo = QtWidgets.QLabel(self.group_box_narmsdata)
        self.table_widget = QtWidgets.QTableWidget(self.group_box_narmsdata)
        self.label_azm = QtWidgets.QLabel(self.group_box_narmsdata)
        self.label_caz = QtWidgets.QLabel(self.group_box_narmsdata)
        self.label_ccv = QtWidgets.QLabel(self.group_box_narmsdata)
        self.label_cep = QtWidgets.QLabel(self.group_box_narmsdata)
        self.label_ceq = QtWidgets.QLabel(self.group_box_narmsdata)
        self.label_chl = QtWidgets.QLabel(self.group_box_narmsdata)
        self.label_gen = QtWidgets.QLabel(self.group_box_narmsdata)
        self.label_cot = QtWidgets.QLabel(self.group_box_narmsdata)
        self.label_fis = QtWidgets.QLabel(self.group_box_narmsdata)
        self.label_ctc = QtWidgets.QLabel(self.group_box_narmsdata)
        self.label_ctx = QtWidgets.QLabel(self.group_box_narmsdata)
        self.label_cip = QtWidgets.QLabel(self.group_box_narmsdata)
        self.label_ffn = QtWidgets.QLabel(self.group_box_narmsdata)
        self.label_cli = QtWidgets.QLabel(self.group_box_narmsdata)
        self.label_fep = QtWidgets.QLabel(self.group_box_narmsdata)
        self.label_ery = QtWidgets.QLabel(self.group_box_narmsdata)
        self.label_fox = QtWidgets.QLabel(self.group_box_narmsdata)
        self.label_nal = QtWidgets.QLabel(self.group_box_narmsdata)
        self.label_mer = QtWidgets.QLabel(self.group_box_narmsdata)
        self.label_imi = QtWidgets.QLabel(self.group_box_narmsdata)
        self.label_ptz = QtWidgets.QLabel(self.group_box_narmsdata)
        self.label_str = QtWidgets.QLabel(self.group_box_narmsdata)
        self.label_tel = QtWidgets.QLabel(self.group_box_narmsdata)
        self.label_smx = QtWidgets.QLabel(self.group_box_narmsdata)
        self.label_tet = QtWidgets.QLabel(self.group_box_narmsdata)
        self.label_kan = QtWidgets.QLabel(self.group_box_narmsdata)
        self.label_tio = QtWidgets.QLabel(self.group_box_narmsdata)
        self.menubar = QtWidgets.QMenuBar(output_window)
        self.statusbar = QtWidgets.QStatusBar(output_window)


    def test_setup_ui(self):
        """
        This function test whether the "setup_ui" function set a correct object name for each
        attributes and check if they are in the correct postition.
        """
        output_window.setObjectName("output_window")
        output_window.resize(884, 824)
        self.centralwidget = QtWidgets.QWidget(output_window)
        self.centralwidget.setObjectName("centralwidget")
        self.group_box_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.group_box_2.setGeometry(QtCore.QRect(10, 90, 421, 241))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.group_box_2.setFont(font)
        self.group_box_2.setAcceptDrops(True)
        self.group_box_2.setObjectName("group_box_2")
        self.label_29 = QtWidgets.QLabel(self.group_box_2)
        self.label_29.setGeometry(QtCore.QRect(10, 146, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.label_2 = QtWidgets.QLabel(self.group_box_2)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.group_box_2)
        self.label.setGeometry(QtCore.QRect(10, 26, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_20 = QtWidgets.QLabel(self.group_box_2)
        self.label_20.setGeometry(QtCore.QRect(10, 50, 35, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.label_18 = QtWidgets.QLabel(self.group_box_2)
        self.label_18.setGeometry(QtCore.QRect(10, 100, 35, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.label_17 = QtWidgets.QLabel(self.group_box_2)
        self.label_17.setGeometry(QtCore.QRect(10, 115, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.label_14 = QtWidgets.QLabel(self.group_box_2)
        self.label_14.setGeometry(QtCore.QRect(10, 130, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.group_box_2)
        self.label_15.setGeometry(QtCore.QRect(10, 160, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.label_13 = QtWidgets.QLabel(self.group_box_2)
        self.label_13.setGeometry(QtCore.QRect(10, 175, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_21 = QtWidgets.QLabel(self.group_box_2)
        self.label_21.setGeometry(QtCore.QRect(30, 80, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.label_19 = QtWidgets.QLabel(self.group_box_2)
        self.label_19.setGeometry(QtCore.QRect(10, 70, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.subject_id = QtWidgets.QLabel(self.group_box_2)
        self.subject_id.setGeometry(QtCore.QRect(130, 26, 251, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.subject_id.setFont(font)
        self.subject_id.setObjectName("subject_id")
        self.hadm_id = QtWidgets.QLabel(self.group_box_2)
        self.hadm_id.setGeometry(QtCore.QRect(130, 40, 251, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.hadm_id.setFont(font)
        self.hadm_id.setObjectName("hadm_id")
        self.age = QtWidgets.QLabel(self.group_box_2)
        self.age.setGeometry(QtCore.QRect(130, 50, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.age.setFont(font)
        self.age.setObjectName("age")
        self.expire_flag = QtWidgets.QLabel(self.group_box_2)
        self.expire_flag.setGeometry(QtCore.QRect(130, 70, 251, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.expire_flag.setFont(font)
        self.expire_flag.setObjectName("expire_flag")
        self.age_death = QtWidgets.QLabel(self.group_box_2)
        self.age_death.setGeometry(QtCore.QRect(130, 80, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.age_death.setFont(font)
        self.age_death.setObjectName("age_death")
        self.gender = QtWidgets.QLabel(self.group_box_2)
        self.gender.setGeometry(QtCore.QRect(130, 100, 251, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.gender.setFont(font)
        self.gender.setObjectName("gender")
        self.ethnicity = QtWidgets.QLabel(self.group_box_2)
        self.ethnicity.setGeometry(QtCore.QRect(130, 110, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ethnicity.setFont(font)
        self.ethnicity.setObjectName("ethnicity")
        self.language = QtWidgets.QLabel(self.group_box_2)
        self.language.setGeometry(QtCore.QRect(130, 130, 251, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.language.setFont(font)
        self.language.setObjectName("language")
        self.marital_status = QtWidgets.QLabel(self.group_box_2)
        self.marital_status.setGeometry(QtCore.QRect(130, 139, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.marital_status.setFont(font)
        self.marital_status.setObjectName("marital_status")
        self.religion = QtWidgets.QLabel(self.group_box_2)
        self.religion.setGeometry(QtCore.QRect(130, 160, 251, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.religion.setFont(font)
        self.religion.setObjectName("religion")
        self.insurance = QtWidgets.QLabel(self.group_box_2)
        self.insurance.setGeometry(QtCore.QRect(130, 170, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.insurance.setFont(font)
        self.insurance.setObjectName("insurance")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(20, 20, 841, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_23.setFont(font)
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setWordWrap(False)
        self.label_23.setObjectName("label_23")
        self.group_box_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.group_box_4.setGeometry(QtCore.QRect(450, 90, 411, 131))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.group_box_4.setFont(font)
        self.group_box_4.setAcceptDrops(True)
        self.group_box_4.setObjectName("group_box_4")
        self.label_22 = QtWidgets.QLabel(self.group_box_4)
        self.label_22.setGeometry(QtCore.QRect(30, 40, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.label_56 = QtWidgets.QLabel(self.group_box_4)
        self.label_56.setGeometry(QtCore.QRect(10, 26, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_56.setFont(font)
        self.label_56.setObjectName("label_56")
        self.label_57 = QtWidgets.QLabel(self.group_box_4)
        self.label_57.setGeometry(QtCore.QRect(10, 50, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_57.setFont(font)
        self.label_57.setObjectName("label_57")
        self.label_58 = QtWidgets.QLabel(self.group_box_4)
        self.label_58.setGeometry(QtCore.QRect(10, 100, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_58.setFont(font)
        self.label_58.setObjectName("label_58")
        self.label_63 = QtWidgets.QLabel(self.group_box_4)
        self.label_63.setGeometry(QtCore.QRect(10, 80, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_63.setFont(font)
        self.label_63.setObjectName("label_63")
        self.label_64 = QtWidgets.QLabel(self.group_box_4)
        self.label_64.setGeometry(QtCore.QRect(10, 70, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_64.setFont(font)
        self.label_64.setObjectName("label_64")
        self.Code = QtWidgets.QLabel(self.group_box_4)
        self.Code.setGeometry(QtCore.QRect(170, 26, 231, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Code.setFont(font)
        self.Code.setObjectName("Code")
        self.Descriptor = QtWidgets.QLabel(self.group_box_4)
        self.Descriptor.setGeometry(QtCore.QRect(170, 40, 231, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Descriptor.setFont(font)
        self.Descriptor.setObjectName("Descriptor")
        self.long_title = QtWidgets.QLabel(self.group_box_4)
        self.long_title.setGeometry(QtCore.QRect(170, 50, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.long_title.setFont(font)
        self.long_title.setObjectName("long_title")
        self.admission_type = QtWidgets.QLabel(self.group_box_4)
        self.admission_type.setGeometry(QtCore.QRect(170, 70, 231, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.admission_type.setFont(font)
        self.admission_type.setObjectName("admission_type")
        self.admit_new = QtWidgets.QLabel(self.group_box_4)
        self.admit_new.setGeometry(QtCore.QRect(170, 80, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.admit_new.setFont(font)
        self.admit_new.setObjectName("admit_new")
        self.disch_new = QtWidgets.QLabel(self.group_box_4)
        self.disch_new.setGeometry(QtCore.QRect(170, 100, 231, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.disch_new.setFont(font)
        self.disch_new.setObjectName("disch_new")
        self.group_box_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.group_box_5.setGeometry(QtCore.QRect(450, 230, 411, 101))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.group_box_5.setFont(font)
        self.group_box_5.setAcceptDrops(True)
        self.group_box_5.setObjectName("group_box_5")
        self.label_67 = QtWidgets.QLabel(self.group_box_5)
        self.label_67.setGeometry(QtCore.QRect(10, 26, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_67.setFont(font)
        self.label_67.setObjectName("label_67")
        self.subject_id_7 = QtWidgets.QLabel(self.group_box_5)
        self.subject_id_7.setGeometry(QtCore.QRect(80, 26, 141, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.subject_id_7.setFont(font)
        self.subject_id_7.setObjectName("subject_id_7")
        self.text_browser = QtWidgets.QTextBrowser(self.group_box_5)
        self.text_browser.setGeometry(QtCore.QRect(90, 30, 311, 61))
        self.text_browser.setObjectName("text_browser")
        self.group_box_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.group_box_3.setGeometry(QtCore.QRect(10, 340, 851, 381))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.group_box_3.setFont(font)
        self.group_box_3.setAcceptDrops(True)
        self.group_box_3.setObjectName("group_box_3")
        self.label_31 = QtWidgets.QLabel(self.group_box_3)
        self.label_31.setGeometry(QtCore.QRect(20, 216, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.label_33 = QtWidgets.QLabel(self.group_box_3)
        self.label_33.setGeometry(QtCore.QRect(10, 170, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.label_62 = QtWidgets.QLabel(self.group_box_3)
        self.label_62.setGeometry(QtCore.QRect(20, 185, 291, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_62.setFont(font)
        self.label_62.setObjectName("label_62")
        self.label_68 = QtWidgets.QLabel(self.group_box_3)
        self.label_68.setGeometry(QtCore.QRect(20, 200, 291, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_68.setFont(font)
        self.label_68.setObjectName("label_68")
        self.label_69 = QtWidgets.QLabel(self.group_box_3)
        self.label_69.setGeometry(QtCore.QRect(20, 230, 291, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_69.setFont(font)
        self.label_69.setObjectName("label_69")
        self.label_70 = QtWidgets.QLabel(self.group_box_3)
        self.label_70.setGeometry(QtCore.QRect(20, 245, 291, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_70.setFont(font)
        self.label_70.setObjectName("label_70")
        self.table_widget = QtWidgets.QTableWidget(self.group_box_3)
        self.table_widget.setGeometry(QtCore.QRect(10, 30, 831, 121))
        self.table_widget.setObjectName("table_widget")
        self.table_widget.setColumnCount(35)
        self.table_widget.setRowCount(1)
        self.label_71 = QtWidgets.QLabel(self.group_box_3)
        self.label_71.setGeometry(QtCore.QRect(20, 260, 291, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_71.setFont(font)
        self.label_71.setObjectName("label_71")
        self.label_72 = QtWidgets.QLabel(self.group_box_3)
        self.label_72.setGeometry(QtCore.QRect(20, 270, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_72.setFont(font)
        self.label_72.setObjectName("label_72")
        self.label_73 = QtWidgets.QLabel(self.group_box_3)
        self.label_73.setGeometry(QtCore.QRect(20, 290, 291, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_73.setFont(font)
        self.label_73.setObjectName("label_73")
        self.label_74 = QtWidgets.QLabel(self.group_box_3)
        self.label_74.setGeometry(QtCore.QRect(20, 300, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_74.setFont(font)
        self.label_74.setObjectName("label_74")
        self.label_75 = QtWidgets.QLabel(self.group_box_3)
        self.label_75.setGeometry(QtCore.QRect(20, 320, 291, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_75.setFont(font)
        self.label_75.setObjectName("label_75")
        self.label_76 = QtWidgets.QLabel(self.group_box_3)
        self.label_76.setGeometry(QtCore.QRect(20, 330, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_76.setFont(font)
        self.label_76.setObjectName("label_76")
        self.label_77 = QtWidgets.QLabel(self.group_box_3)
        self.label_77.setGeometry(QtCore.QRect(350, 330, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_77.setFont(font)
        self.label_77.setObjectName("label_77")
        self.label_32 = QtWidgets.QLabel(self.group_box_3)
        self.label_32.setGeometry(QtCore.QRect(350, 216, 291, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.label_78 = QtWidgets.QLabel(self.group_box_3)
        self.label_78.setGeometry(QtCore.QRect(350, 300, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_78.setFont(font)
        self.label_78.setObjectName("label_78")
        self.label_79 = QtWidgets.QLabel(self.group_box_3)
        self.label_79.setGeometry(QtCore.QRect(350, 230, 291, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_79.setFont(font)
        self.label_79.setObjectName("label_79")
        self.label_80 = QtWidgets.QLabel(self.group_box_3)
        self.label_80.setGeometry(QtCore.QRect(350, 245, 291, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_80.setFont(font)
        self.label_80.setObjectName("label_80")
        self.label_81 = QtWidgets.QLabel(self.group_box_3)
        self.label_81.setGeometry(QtCore.QRect(350, 185, 291, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_81.setFont(font)
        self.label_81.setObjectName("label_81")
        self.label_82 = QtWidgets.QLabel(self.group_box_3)
        self.label_82.setGeometry(QtCore.QRect(350, 290, 291, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_82.setFont(font)
        self.label_82.setObjectName("label_82")
        self.label_83 = QtWidgets.QLabel(self.group_box_3)
        self.label_83.setGeometry(QtCore.QRect(350, 200, 291, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_83.setFont(font)
        self.label_83.setObjectName("label_83")
        self.label_84 = QtWidgets.QLabel(self.group_box_3)
        self.label_84.setGeometry(QtCore.QRect(350, 270, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_84.setFont(font)
        self.label_84.setObjectName("label_84")
        self.label_85 = QtWidgets.QLabel(self.group_box_3)
        self.label_85.setGeometry(QtCore.QRect(350, 260, 291, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_85.setFont(font)
        self.label_85.setObjectName("label_85")
        self.label_86 = QtWidgets.QLabel(self.group_box_3)
        self.label_86.setGeometry(QtCore.QRect(350, 320, 291, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_86.setFont(font)
        self.label_86.setObjectName("label_86")
        self.label_87 = QtWidgets.QLabel(self.group_box_3)
        self.label_87.setGeometry(QtCore.QRect(670, 230, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_87.setFont(font)
        self.label_87.setObjectName("label_87")
        self.label_88 = QtWidgets.QLabel(self.group_box_3)
        self.label_88.setGeometry(QtCore.QRect(670, 216, 181, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_88.setFont(font)
        self.label_88.setObjectName("label_88")
        self.label_89 = QtWidgets.QLabel(self.group_box_3)
        self.label_89.setGeometry(QtCore.QRect(670, 185, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_89.setFont(font)
        self.label_89.setObjectName("label_89")
        self.label_90 = QtWidgets.QLabel(self.group_box_3)
        self.label_90.setGeometry(QtCore.QRect(670, 245, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_90.setFont(font)
        self.label_90.setObjectName("label_90")
        self.label_91 = QtWidgets.QLabel(self.group_box_3)
        self.label_91.setGeometry(QtCore.QRect(670, 270, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_91.setFont(font)
        self.label_91.setObjectName("label_91")
        self.label_92 = QtWidgets.QLabel(self.group_box_3)
        self.label_92.setGeometry(QtCore.QRect(670, 290, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_92.setFont(font)
        self.label_92.setObjectName("label_92")
        self.label_93 = QtWidgets.QLabel(self.group_box_3)
        self.label_93.setGeometry(QtCore.QRect(670, 260, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_93.setFont(font)
        self.label_93.setObjectName("label_93")
        self.label_94 = QtWidgets.QLabel(self.group_box_3)
        self.label_94.setGeometry(QtCore.QRect(670, 300, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_94.setFont(font)
        self.label_94.setObjectName("label_94")
        self.label_95 = QtWidgets.QLabel(self.group_box_3)
        self.label_95.setGeometry(QtCore.QRect(670, 200, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_95.setFont(font)
        self.label_95.setObjectName("label_95")
        self.label_97 = QtWidgets.QLabel(self.group_box_3)
        self.label_97.setGeometry(QtCore.QRect(670, 320, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_97.setFont(font)
        self.label_97.setObjectName("label_97")
        output_window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(output_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 884, 18))
        self.menubar.setObjectName("menubar")
        output_window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(output_window)
        self.statusbar.setObjectName("statusbar")
        output_window.setStatusBar(self.statusbar)


        self.assertEqual(output_window.objectName(), "output_window")
        self.assertEqual(output_window.size(), QtCore.QSize(884, 824))
        self.assertEqual(self.centralwidget.objectName(), "centralwidget")
        self.assertEqual(self.group_box_2.geometry(), QtCore.QRect(10, 90, 421, 241))
        self.assertEqual(self.group_box_2.objectName(), "group_box_2")
        self.assertEqual(self.label_29.geometry(), QtCore.QRect(10, 146, 121, 20))
        self.assertEqual(self.label_29.objectName(), "label_29")
        self.assertEqual(self.label_2.geometry(), QtCore.QRect(10, 40, 91, 21))
        self.assertEqual(self.label_2.objectName(), "label_2")
        self.assertEqual(self.label.geometry(), QtCore.QRect(10, 26, 111, 21))
        self.assertEqual(self.label.objectName(), "label")
        self.assertEqual(self.label_20.geometry(), QtCore.QRect(10, 50, 35, 31))
        self.assertEqual(self.label_20.objectName(), "label_20")
        self.assertEqual(self.label_18.geometry(), QtCore.QRect(10, 100, 35, 21))
        self.assertEqual(self.label_18.objectName(), "label_18")
        self.assertEqual(self.label_17.geometry(), QtCore.QRect(10, 115, 41, 21))
        self.assertEqual(self.label_17.objectName(), "label_17")
        self.assertEqual(self.label_14.geometry(), QtCore.QRect(10, 130, 121, 21))
        self.assertEqual(self.label_14.objectName(), "label_14")
        self.assertEqual(self.label_15.geometry(), QtCore.QRect(10, 160, 111, 21))
        self.assertEqual(self.label_15.objectName(), "label_15")
        self.assertEqual(self.label_13.geometry(), QtCore.QRect(10, 175, 121, 21))
        self.assertEqual(self.label_13.objectName(), "label_13")
        self.assertEqual(self.label_21.geometry(), QtCore.QRect(30, 80, 81, 31))
        self.assertEqual(self.label_21.objectName(), "label_21")
        self.assertEqual(self.label_19.geometry(), QtCore.QRect(10, 70, 71, 21))
        self.assertEqual(self.label_19.objectName(), "label_19")
        self.assertEqual(self.subject_id.geometry(), QtCore.QRect(130, 26, 251, 20))
        self.assertEqual(self.subject_id.objectName(), "subject_id")
        self.assertEqual(self.hadm_id.geometry(), QtCore.QRect(130, 40, 251, 21))
        self.assertEqual(self.hadm_id.objectName(), "hadm_id")
        self.assertEqual(self.age.geometry(), QtCore.QRect(130, 50, 251, 31))
        self.assertEqual(self.age.objectName(), "age")
        self.assertEqual(self.expire_flag.geometry(), QtCore.QRect(130, 70, 251, 21))
        self.assertEqual(self.expire_flag.objectName(), "expire_flag")
        self.assertEqual(self.age_death.geometry(), QtCore.QRect(130, 80, 251, 31))
        self.assertEqual(self.age_death.objectName(), "age_death")
        self.assertEqual(self.gender.geometry(), QtCore.QRect(130, 100, 251, 21))
        self.assertEqual(self.gender.objectName(), "gender")
        self.assertEqual(self.ethnicity.geometry(), QtCore.QRect(130, 110, 251, 31))
        self.assertEqual(self.ethnicity.objectName(), "ethnicity")
        self.assertEqual(self.language.geometry(), QtCore.QRect(130, 130, 251, 21))
        self.assertEqual(self.language.objectName(), "language")
        self.assertEqual(self.marital_status.geometry(), QtCore.QRect(130, 139, 251, 31))
        self.assertEqual(self.marital_status.objectName(), "marital_status")
        self.assertEqual(self.religion.geometry(), QtCore.QRect(130, 160, 251, 21))
        self.assertEqual(self.religion.objectName(), "religion")
        self.assertEqual(self.insurance.geometry(), QtCore.QRect(130, 170, 251, 31))
        self.assertEqual(self.insurance.objectName(), "insurance")
        self.assertEqual(self.label_23.geometry(), QtCore.QRect(20, 20, 841, 41))
        self.assertEqual(self.label_23.objectName(), "label_23")
        self.assertEqual(self.group_box_4.geometry(), QtCore.QRect(450, 90, 411, 131))
        self.assertEqual(self.group_box_4.objectName(), "group_box_4")
        self.assertEqual(self.label_22.geometry(), QtCore.QRect(30, 40, 81, 21))
        self.assertEqual(self.label_22.objectName(), "label_22")
        self.assertEqual(self.label_56.geometry(), QtCore.QRect(10, 26, 161, 21))
        self.assertEqual(self.label_56.objectName(), "label_56")
        self.assertEqual(self.label_57.geometry(), QtCore.QRect(10, 50, 91, 31))
        self.assertEqual(self.label_57.objectName(), "label_57")
        self.assertEqual(self.label_58.geometry(), QtCore.QRect(10, 100, 101, 21))
        self.assertEqual(self.label_58.objectName(), "label_58")
        self.assertEqual(self.label_63.geometry(), QtCore.QRect(10, 80, 91, 31))
        self.assertEqual(self.label_63.objectName(), "label_63")
        self.assertEqual(self.label_64.geometry(), QtCore.QRect(10, 70, 161, 21))
        self.assertEqual(self.label_64.objectName(), "label_64")
        self.assertEqual(self.Code.geometry(), QtCore.QRect(170, 26, 231, 20))
        self.assertEqual(self.Code.objectName(), "Code")
        self.assertEqual(self.Descriptor.geometry(), QtCore.QRect(170, 40, 231, 21))
        self.assertEqual(self.Descriptor.objectName(), "Descriptor")
        self.assertEqual(self.long_title.geometry(), QtCore.QRect(170, 50, 231, 31))
        self.assertEqual(self.long_title.objectName(), "long_title")
        self.assertEqual(self.admission_type.geometry(), QtCore.QRect(170, 70, 231, 21))
        self.assertEqual(self.admission_type.objectName(), "admission_type")
        self.assertEqual(self.admit_new.geometry(), QtCore.QRect(170, 80, 231, 31))
        self.assertEqual(self.admit_new.objectName(), "admit_new")
        self.assertEqual(self.disch_new.geometry(), QtCore.QRect(170, 100, 231, 21))
        self.assertEqual(self.disch_new.objectName(), "disch_new")
        self.assertEqual(self.group_box_5.geometry(), QtCore.QRect(450, 230, 411, 101))
        self.assertEqual(self.group_box_5.objectName(), "group_box_5")
        self.assertEqual(self.label_67.geometry(), QtCore.QRect(10, 26, 111, 21))
        self.assertEqual(self.label_67.objectName(), "label_67")
        self.assertEqual(self.subject_id_7.geometry(), QtCore.QRect(80, 26, 141, 20))
        self.assertEqual(self.subject_id_7.objectName(), "subject_id_7")
        self.assertEqual(self.text_browser.geometry(), QtCore.QRect(90, 30, 311, 61))
        self.assertEqual(self.text_browser.objectName(), "text_browser")
        self.assertEqual(self.group_box_3.geometry(), QtCore.QRect(10, 340, 851, 381))
        self.assertEqual(self.group_box_3.objectName(), "group_box_3")
        self.assertEqual(self.label_31.geometry(), QtCore.QRect(20, 216, 81, 20))
        self.assertEqual(self.label_31.objectName(), "label_31")
        self.assertEqual(self.label_33.geometry(), QtCore.QRect(10, 170, 81, 21))
        self.assertEqual(self.label_33.objectName(), "label_33")
        self.assertEqual(self.label_62.geometry(), QtCore.QRect(20, 185, 291, 21))
        self.assertEqual(self.label_62.objectName(), "label_62")
        self.assertEqual(self.label_68.geometry(), QtCore.QRect(20, 200, 291, 21))
        self.assertEqual(self.label_68.objectName(), "label_68")
        self.assertEqual(self.label_69.geometry(), QtCore.QRect(20, 230, 291, 21))
        self.assertEqual(self.label_69.objectName(), "label_69")
        self.assertEqual(self.label_70.geometry(), QtCore.QRect(20, 245, 291, 21))
        self.assertEqual(self.label_70.objectName(), "label_70")
        self.assertEqual(self.table_widget.geometry(), QtCore.QRect(10, 30, 831, 121))
        self.assertEqual(self.table_widget.objectName(), "table_widget")
        self.assertEqual(self.table_widget.columnCount(), 35)
        self.assertEqual(self.table_widget.rowCount(), 1)
        self.assertEqual(self.label_71.geometry(), QtCore.QRect(20, 260, 291, 21))
        self.assertEqual(self.label_71.objectName(), "label_71")
        self.assertEqual(self.label_72.geometry(), QtCore.QRect(20, 270, 291, 31))
        self.assertEqual(self.label_72.objectName(), "label_72")
        self.assertEqual(self.label_73.geometry(), QtCore.QRect(20, 290, 291, 21))
        self.assertEqual(self.label_73.objectName(), "label_73")
        self.assertEqual(self.label_74.geometry(), QtCore.QRect(20, 300, 291, 31))
        self.assertEqual(self.label_74.objectName(), "label_74")
        self.assertEqual(self.label_75.geometry(), QtCore.QRect(20, 320, 291, 21))
        self.assertEqual(self.label_75.objectName(), "label_75")
        self.assertEqual(self.label_76.geometry(), QtCore.QRect(20, 330, 291, 31))
        self.assertEqual(self.label_76.objectName(), "label_76")
        self.assertEqual(self.label_77.geometry(), QtCore.QRect(350, 330, 291, 31))
        self.assertEqual(self.label_77.objectName(), "label_77")
        self.assertEqual(self.label_32.geometry(), QtCore.QRect(350, 216, 291, 20))
        self.assertEqual(self.label_32.objectName(), "label_32")
        self.assertEqual(self.label_78.geometry(), QtCore.QRect(350, 300, 291, 31))
        self.assertEqual(self.label_78.objectName(), "label_78")
        self.assertEqual(self.label_79.geometry(), QtCore.QRect(350, 230, 291, 21))
        self.assertEqual(self.label_79.objectName(), "label_79")
        self.assertEqual(self.label_80.geometry(), QtCore.QRect(350, 245, 291, 21))
        self.assertEqual(self.label_80.objectName(), "label_80")
        self.assertEqual(self.label_81.geometry(), QtCore.QRect(350, 185, 291, 21))
        self.assertEqual(self.label_81.objectName(), "label_81")
        self.assertEqual(self.label_82.geometry(), QtCore.QRect(350, 290, 291, 21))
        self.assertEqual(self.label_82.objectName(), "label_82")
        self.assertEqual(self.label_83.geometry(), QtCore.QRect(350, 200, 291, 21))
        self.assertEqual(self.label_83.objectName(), "label_83")
        self.assertEqual(self.label_84.geometry(), QtCore.QRect(350, 270, 291, 31))
        self.assertEqual(self.label_84.objectName(), "label_84")
        self.assertEqual(self.label_85.geometry(), QtCore.QRect(350, 260, 291, 21))
        self.assertEqual(self.label_85.objectName(), "label_85")
        self.assertEqual(self.label_86.geometry(), QtCore.QRect(350, 320, 291, 21))
        self.assertEqual(self.label_86.objectName(), "label_86")
        self.assertEqual(self.label_87.geometry(), QtCore.QRect(670, 230, 181, 21))
        self.assertEqual(self.label_87.objectName(), "label_87")
        self.assertEqual(self.label_88.geometry(), QtCore.QRect(670, 216, 181, 20))
        self.assertEqual(self.label_88.objectName(), "label_88")
        self.assertEqual(self.label_89.geometry(), QtCore.QRect(670, 185, 181, 21))
        self.assertEqual(self.label_89.objectName(), "label_89")
        self.assertEqual(self.label_90.geometry(), QtCore.QRect(670, 245, 181, 21))
        self.assertEqual(self.label_90.objectName(), "label_90")
        self.assertEqual(self.label_91.geometry(), QtCore.QRect(670, 270, 181, 31))
        self.assertEqual(self.label_91.objectName(), "label_91")
        self.assertEqual(self.label_92.geometry(), QtCore.QRect(670, 290, 181, 21))
        self.assertEqual(self.label_92.objectName(), "label_92")
        self.assertEqual(self.label_93.geometry(), QtCore.QRect(670, 260, 181, 21))
        self.assertEqual(self.label_93.objectName(), "label_93")
        self.assertEqual(self.label_94.geometry(), QtCore.QRect(670, 300, 181, 31))
        self.assertEqual(self.label_94.objectName(), "label_94")
        self.assertEqual(self.label_95.geometry(), QtCore.QRect(670, 200, 181, 21))
        self.assertEqual(self.label_95.objectName(), "label_95")
        self.assertEqual(self.label_97.geometry(), QtCore.QRect(670, 320, 181, 21))
        self.assertEqual(self.label_97.objectName(), "label_97")
        self.assertEqual(self.menubar.geometry(), QtCore.QRect(0, 0, 884, 18))
        self.assertEqual(self.menubar.objectName(), "menubar")
        self.assertEqual(self.statusbar.objectName(), "statusbar")


    def test_query_values(self):
        """
        This function test whether the "query_values" function get a correct values from 
        'get_report' and check if it prints the values in the right order. 
        """
        variable, table_narms = UiOutput1Window.get_report(self, 61, 1947)
        self.subject_id.setText(": " + str(variable['subject_id']))
        self.hadm_id.setText(": " + str(variable['hadm_id']))
        self.age.setText(": " + str(variable['age']))
        self.expire_flag.setText(": " + str(variable['expire_flag']))
        self.age_death.setText(": " + str(variable['age_death']))
        self.gender.setText(": " + str(variable['gender']))
        self.ethnicity.setText(": " + str(variable['ethnicity']))
        self.language.setText(": " + str(variable['language']))
        self.marital_status.setText(": " + str(variable['marital_status']))
        self.religion.setText(": " + str(variable['religion']))
        self.insurance.setText(": " + str(variable['insurance']))

        self.code.setText(": " + str(variable['Code']))
        self.descriptor.setText(": " + str(variable['Descriptor']))
        self.long_title.setText(": " + str(variable['long_title']))
        self.admission_type.setText(": " + str(variable['admission_type']))
        self.admit_new.setText(": " + str(variable['admit_new']))
        self.disch_new.setText(": " + str(variable['disch_new']))
        self.text_browser.setText(str(variable['drug']))

        self.assertEqual(self.subject_id.text(), ": 61")
        self.assertEqual(self.hadm_id.text(), ": 189535")
        self.assertEqual(self.age.text(), ": 55")
        self.assertEqual(self.expire_flag.text(), ": Death")
        self.assertEqual(self.age_death.text(), ": 55")
        self.assertEqual(self.gender.text(), ": M")
        self.assertEqual(self.ethnicity.text(), ": WHITE")
        self.assertEqual(self.language.text(), ": nan")
        self.assertEqual(self.marital_status.text(), ": MARRIED")
        self.assertEqual(self.religion.text(), ": CATHOLIC")
        self.assertEqual(self.insurance.text(), ": Private")

        self.assertEqual(self.code.text(), ": 99591")
        self.assertEqual(self.descriptor.text(), ": Salmonella sepsis")
        self.assertEqual(self.long_title.text(), ": Acidosis")
        self.assertEqual(self.admission_type.text(), ": EMERGENCY")
        #self.assertEqual(self.admit_new.text(), ": 2002-01-04")
        #self.assertEqual(self.disch_new.text(), ": 2002-02-03")
        word = "Amino Acids 4.25% W/ Dextrose 5% ,  Calcium Gluconate ,  Digoxin ,  Potassium Chloride ,  Potassium Chloride ,  Multivitamin IV ,  Heparin Flush PICC (100 units/ml) ,  Digoxin ,  Digoxin ,  Insulin ,  Hydrocortisone Na Succ. ,  Syringe ,  Insulin ,  Insulin ,  NS ,  Hydrocortisone Na Succ. ,  Digoxin ,  Neutra-Phos ,  Vial ,  Vial ,  Sodium Phosphate ,  Potassium Chloride ,  Hydrocortisone Na Succ. ,  Potassium Chloride ,  Daptomycin ,  NS ,  Levofloxacin ,  Potassium Chloride ,  SW ,  Potassium Chloride ,  Potassium Chloride ,  NS ,  Hydrocortisone Na Succ. ,  Vial ,  Diltiazem ,  NS ,  Potassium Chloride ,  Potassium Chloride ,  Potassium Chloride ,  Potassium Phosphate ,  SW ,  SW ,  SW ,  Spironolactone ,  Vial ,  Filgrastim ,  Potassium Chloride ,  Potassium Chloride ,  Hydrocortisone Na Succ. ,  Caspofungin"
        self.assertEqual(self.text_browser.toPlainText(), word)

    def test_load_data(self):
        """Printing narms data to column in the UI"""
        self.table_widget.setGeometry(QtCore.QRect(10, 30, 831, 121))
        self.table_widget.setObjectName("table_widget")
        self.table_widget.setColumnCount(35)
        self.table_widget.setRowCount(1)
        variable, data = UiOutput1Window.get_report(self, 61, 1947)
        i = 0
        for key in data.keys():
            key = QtWidgets.QTableWidgetItem(key)
            key.setTextAlignment(QtCore.Qt.AlignCenter)
            self.table_widget.setHorizontalHeaderItem(i, key)
            i += 1

        i = 0
        for value in data.values():
            value = QtWidgets.QTableWidgetItem(value)
            value.setTextAlignment(QtCore.Qt.AlignCenter)
            self.table_widget.setItem(0, i, value)
            i += 1
        
        self.assertEqual(self.table_widget.horizontalHeaderItem(0).text(), "Data_Year")
        self.assertEqual(self.table_widget.horizontalHeaderItem(1).text(), "Age_Group")
        self.assertEqual(self.table_widget.horizontalHeaderItem(2).text(), "Specimen_ID")
        self.assertEqual(self.table_widget.horizontalHeaderItem(3).text(), "Resistance_Pattern")
        self.assertEqual(self.table_widget.horizontalHeaderItem(4).text(), "AMI_Concl")
        self.assertEqual(self.table_widget.horizontalHeaderItem(5).text(), "AMP_Concl")
        self.assertEqual(self.table_widget.horizontalHeaderItem(6).text(), "ATM_Concl")
        self.assertEqual(self.table_widget.horizontalHeaderItem(7).text(), "AUG_Concl")
        self.assertEqual(self.table_widget.horizontalHeaderItem(8).text(), "AXO_Concl")
        self.assertEqual(self.table_widget.horizontalHeaderItem(9).text(), "AZM_Concl")
        self.assertEqual(self.table_widget.horizontalHeaderItem(10).text(), "CAZ_Concl")
        self.assertEqual(self.table_widget.horizontalHeaderItem(11).text(), "CCV_Concl")
        self.assertEqual(self.table_widget.horizontalHeaderItem(12).text(), "CEP_Concl")
        self.assertEqual(self.table_widget.horizontalHeaderItem(13).text(), "CEQ_Concl")
        self.assertEqual(self.table_widget.horizontalHeaderItem(14).text(), "CHL_Concl")
        self.assertEqual(self.table_widget.horizontalHeaderItem(15).text(), "CIP_Concl")
        self.assertEqual(self.table_widget.horizontalHeaderItem(16).text(), "CLI_Concl")
        self.assertEqual(self.table_widget.horizontalHeaderItem(17).text(), "COT_Concl")
        self.assertEqual(self.table_widget.horizontalHeaderItem(18).text(), "CTC_Concl")
        self.assertEqual(self.table_widget.horizontalHeaderItem(19).text(), "CTX_Concl")
        self.assertEqual(self.table_widget.horizontalHeaderItem(20).text(), "ERY_Concl")
        self.assertEqual(self.table_widget.horizontalHeaderItem(21).text(), "FEP_Concl")
        self.assertEqual(self.table_widget.horizontalHeaderItem(22).text(), "FFN_Concl")
        self.assertEqual(self.table_widget.horizontalHeaderItem(23).text(), "FIS_Concl")
        self.assertEqual(self.table_widget.horizontalHeaderItem(24).text(), "FOX_Concl")
        self.assertEqual(self.table_widget.horizontalHeaderItem(25).text(), "GEN_Concl")
        self.assertEqual(self.table_widget.horizontalHeaderItem(26).text(), "IMI_Concl")
        self.assertEqual(self.table_widget.horizontalHeaderItem(27).text(), "KAN_Concl")
        self.assertEqual(self.table_widget.horizontalHeaderItem(28).text(), "NAL_Concl")
        self.assertEqual(self.table_widget.horizontalHeaderItem(29).text(), "PTZ_Concl")
        self.assertEqual(self.table_widget.horizontalHeaderItem(30).text(), "SMX_Concl")
        self.assertEqual(self.table_widget.horizontalHeaderItem(31).text(), "STR_Concl")
        self.assertEqual(self.table_widget.horizontalHeaderItem(32).text(), "TEL_Concl")
        self.assertEqual(self.table_widget.horizontalHeaderItem(33).text(), "TET_Concl")
        self.assertEqual(self.table_widget.horizontalHeaderItem(34).text(), "TIO_Concl")

        columnvalue = ['2002', '50-59', '18', '4', '0', '1', '0', '0', '0', '0', '0', '0',
        '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1',
        '0', '0', '1', '4', '0', '4', '0']

        for i in range(0, 35):
            self.assertEqual(self.table_widget.item(0,i).text(), columnvalue[i])

    def test_retranslate_ui(self):
        """
        This function test whether the "test_retranslate_ui" set a correct title/text
        for each attributes.
        """
        output_window.setWindowTitle(_translate("output_window", "MainWindow"))
        self.group_box_patientinfo.setTitle(_translate("output_window", "Patient Information"))
        self.label_marital.setText(_translate("output_window", "Marital Status"))
        self.label_hospitalid.setText(_translate("output_window", "Hospital Visit ID"))
        self.label_patientid.setText(_translate("output_window", "Patient ID"))
        self.label_age.setText(_translate("output_window", "Age"))
        self.label_gender.setText(_translate("output_window", "Gender"))
        self.label_ethnic.setText(_translate("output_window", "Ethnicity"))
        self.label_language.setText(_translate("output_window", "Primary Language"))
        self.label_religion.setText(_translate("output_window", "Religion"))
        self.label_insurance.setText(_translate("output_window", "Insurance"))
        self.label_deathage.setText(_translate("output_window", "Age of Death"))
        self.label_deceased.setText(_translate("output_window", "Deceased"))
        self.subject_id.setText(_translate("output_window", ": "))
        self.hadm_id.setText(_translate("output_window", ":"))
        self.age.setText(_translate("output_window", ":"))
        self.expire_flag.setText(_translate("output_window", ":"))
        self.age_death.setText(_translate("output_window", ":"))
        self.gender.setText(_translate("output_window", ":"))
        self.ethnicity.setText(_translate("output_window", ":"))
        self.language.setText(_translate("output_window", ":"))
        self.marital_status.setText(_translate("output_window", ":"))
        self.religion.setText(_translate("output_window", ":"))
        self.insurance.setText(_translate("output_window", ":"))
        self.label_title.setText(_translate("output_window", "PATIENT CASE REPORT FORM"))
        self.group_box_diseaseinfo.setTitle(_translate("output_window", "Disease Information"))
        self.label_descriptor.setText(_translate("output_window", "Descriptor"))
        self.label_diagnosiscode.setText(_translate("output_window", "Condition Diagnosis Code"))
        self.label_alldiagnoses.setText(_translate("output_window", "All Diagnoses"))
        self.label_dischargedate.setText(_translate("output_window", "Discharge Date"))
        self.label_admissiondate.setText(_translate("output_window", "Admission Date"))
        self.label_admissiontype.setText(_translate("output_window", "Hospital Admission Type"))
        self.code.setText(_translate("output_window", ": "))
        self.descriptor.setText(_translate("output_window", ":"))
        self.long_title.setText(_translate("output_window", ":"))
        self.admission_type.setText(_translate("output_window", ":"))
        self.admit_new.setText(_translate("output_window", ":"))
        self.disch_new.setText(_translate("output_window", ":"))
        self.group_box_prescriptioninfo.setTitle(_translate("output_window",
                                                            "Prescription Information"))
        self.label_medication.setText(_translate("output_window", "Medication"))
        self.label_doublecolon.setText(_translate("output_window", ": "))
        self.group_box_narmsdata.setTitle(_translate("output_window", "NARMS Data"))
        self.label_atm.setText(_translate("output_window", "ATM Aztreonam"))
        self.label_dictionary.setText(_translate("output_window", "Dictionary"))
        self.label_ami.setText(_translate("output_window", "AMI Amikacin"))
        self.label_amp.setText(_translate("output_window", "AMP Ampicillin"))
        self.label_aug.setText(_translate("output_window", "AUG Amoxicillin-clavulanic acid"))
        self.label_axo.setText(_translate("output_window", "AXO Ceftriaxone"))
        self.label_azm.setText(_translate("output_window", "AZM Azithromycin"))
        self.label_caz.setText(_translate("output_window", "CAZ Ceftazidime"))
        self.label_ccv.setText(_translate("output_window", "CCV Ceftazidime-clavulanic acid"))
        self.label_cep.setText(_translate("output_window", "CEP Cephalothin"))
        self.label_ceq.setText(_translate("output_window", "CEQ Cefquinome"))
        self.label_chl.setText(_translate("output_window", "CHL Chloramphenicol"))
        self.label_gen.setText(_translate("output_window", "GEN Gentamicin"))
        self.label_cot.setText(_translate("output_window", "COT Trimethoprim-sulfamethoxazole"))
        self.label_fis.setText(_translate("output_window", "FIS Sulfisoxazole"))
        self.label_ctc.setText(_translate("output_window", "CTC Cefotaxime-clavulanic acid"))
        self.label_ctx.setText(_translate("output_window", "CTX Cefotaxime"))
        self.label_cip.setText(_translate("output_window", "CIP Ciprofloxacin"))
        self.label_ffn.setText(_translate("output_window", "FFN Florfenicol"))
        self.label_cli.setText(_translate("output_window", "CLI Clindamycin"))
        self.label_fep.setText(_translate("output_window", "FEP Cefepime"))
        self.label_ery.setText(_translate("output_window", "ERY Erythromycin"))
        self.label_fox.setText(_translate("output_window", "FOX Cefoxitin"))
        self.label_nal.setText(_translate("output_window", "NAL Naladixic acid"))
        self.label_mer.setText(_translate("output_window", "MER Meropenem"))
        self.label_imi.setText(_translate("output_window", "IMI Imipenem"))
        self.label_ptz.setText(_translate("output_window", "PTZ Piperacillin-tazobactam"))
        self.label_str.setText(_translate("output_window", "STR Streptomycin"))
        self.label_tel.setText(_translate("output_window", "TEL Telithromycin"))
        self.label_smx.setText(_translate("output_window", "SMX Sulfamethoxazole"))
        self.label_tet.setText(_translate("output_window", "TET Tetracycline"))
        self.label_kan.setText(_translate("output_window", "KAN Kanamycin"))
        self.label_tio.setText(_translate("output_window", "TIO Ceftiofur"))

        self.assertEqual(output_window.windowTitle(), "MainWindow")
        self.assertEqual(self.group_box_patientinfo.title(), "Patient Information")
        self.assertEqual(self.label_marital.text(), "Marital Status")
        self.assertEqual(self.label_hospitalid.text(), "Hospital Visit ID")
        self.assertEqual(self.label_patientid.text(), "Patient ID")
        self.assertEqual(self.label_age.text(), "Age")
        self.assertEqual(self.label_gender.text(), "Gender")
        self.assertEqual(self.label_ethnic.text(), "Ethnicity")
        self.assertEqual(self.label_language.text(), "Primary Language")
        self.assertEqual(self.label_religion.text(), "Religion")
        self.assertEqual(self.label_insurance.text(), "Insurance")
        self.assertEqual(self.label_deathage.text(), "Age of Death")
        self.assertEqual(self.label_deceased.text(), "Deceased")
        self.assertEqual(self.subject_id.text(), ": ")
        self.assertEqual(self.hadm_id.text(), ":")
        self.assertEqual(self.age.text(), ":")
        self.assertEqual(self.expire_flag.text(), ":")
        self.assertEqual(self.age_death.text(), ":")
        self.assertEqual(self.gender.text(), ":")
        self.assertEqual(self.ethnicity.text(), ":")
        self.assertEqual(self.language.text(), ":")
        self.assertEqual(self.marital_status.text(), ":")
        self.assertEqual(self.religion.text(), ":")
        self.assertEqual(self.insurance.text(), ":")
        self.assertEqual(self.label_title.text(), "PATIENT CASE REPORT FORM")
        self.assertEqual(self.group_box_diseaseinfo.title(), "Disease Information")
        self.assertEqual(self.label_descriptor.text(), "Descriptor")
        self.assertEqual(self.label_diagnosiscode.text(), "Condition Diagnosis Code")
        self.assertEqual(self.label_alldiagnoses.text(), "All Diagnoses")
        self.assertEqual(self.label_dischargedate.text(), "Discharge Date")
        self.assertEqual(self.label_admissiondate.text(), "Admission Date")
        self.assertEqual(self.label_admissiontype.text(), "Hospital Admission Type")
        self.assertEqual(self.code.text(), ": ")
        self.assertEqual(self.descriptor.text(), ":")
        self.assertEqual(self.long_title.text(), ":")
        self.assertEqual(self.admission_type.text(), ":")
        self.assertEqual(self.admit_new.text(), ":")
        self.assertEqual(self.disch_new.text(), ":")
        self.assertEqual(self.group_box_prescriptioninfo.title(),
                                                            "Prescription Information")
        self.assertEqual(self.label_medication.text(), "Medication")
        self.assertEqual(self.label_doublecolon.text(), ": ")
        self.assertEqual(self.group_box_narmsdata.title(), "NARMS Data")
        self.assertEqual(self.label_atm.text(), "ATM Aztreonam")
        self.assertEqual(self.label_dictionary.text(), "Dictionary")
        self.assertEqual(self.label_ami.text(), "AMI Amikacin")
        self.assertEqual(self.label_amp.text(), "AMP Ampicillin")
        self.assertEqual(self.label_aug.text(), "AUG Amoxicillin-clavulanic acid")
        self.assertEqual(self.label_axo.text(), "AXO Ceftriaxone")
        self.assertEqual(self.label_azm.text(), "AZM Azithromycin")
        self.assertEqual(self.label_caz.text(), "CAZ Ceftazidime")
        self.assertEqual(self.label_ccv.text(), "CCV Ceftazidime-clavulanic acid")
        self.assertEqual(self.label_cep.text(), "CEP Cephalothin")
        self.assertEqual(self.label_ceq.text(), "CEQ Cefquinome")
        self.assertEqual(self.label_chl.text(), "CHL Chloramphenicol")
        self.assertEqual(self.label_gen.text(), "GEN Gentamicin")
        self.assertEqual(self.label_cot.text(), "COT Trimethoprim-sulfamethoxazole")
        self.assertEqual(self.label_fis.text(), "FIS Sulfisoxazole")
        self.assertEqual(self.label_ctc.text(), "CTC Cefotaxime-clavulanic acid")
        self.assertEqual(self.label_ctx.text(), "CTX Cefotaxime")
        self.assertEqual(self.label_cip.text(), "CIP Ciprofloxacin")
        self.assertEqual(self.label_ffn.text(), "FFN Florfenicol")
        self.assertEqual(self.label_cli.text(), "CLI Clindamycin")
        self.assertEqual(self.label_fep.text(), "FEP Cefepime")
        self.assertEqual(self.label_ery.text(), "ERY Erythromycin")
        self.assertEqual(self.label_fox.text(), "FOX Cefoxitin")
        self.assertEqual(self.label_nal.text(), "NAL Naladixic acid")
        self.assertEqual(self.label_mer.text(), "MER Meropenem")
        self.assertEqual(self.label_imi.text(), "IMI Imipenem")
        self.assertEqual(self.label_ptz.text(), "PTZ Piperacillin-tazobactam")
        self.assertEqual(self.label_str.text(), "STR Streptomycin")
        self.assertEqual(self.label_tel.text(), "TEL Telithromycin")
        self.assertEqual(self.label_smx.text(), "SMX Sulfamethoxazole")
        self.assertEqual(self.label_tet.text(), "TET Tetracycline")
        self.assertEqual(self.label_kan.text(), "KAN Kanamycin")
        self.assertEqual(self.label_tio.text(), "TIO Ceftiofur")


if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    output_window = QtWidgets.QMainWindow()
    _translate = QtCore.QCoreApplication.translate
        
    unittest.main()
