"""
This test file is used to test function in MainWindow.py in EHRTeam
"""
import sys
import unittest
import os.path
from PyQt5 import QtCore, QtGui, QtWidgets
from report_ui import UiOutput1Window
from output_pdf import get_report as pdf_get_report

class TestFunctions(unittest.TestCase):
    """
    Unittest class
    """
    def test_setup_ui(self):
        """
        This function test whether the "setup_ui" function set a correct object name for each
        attributes and check if they are in the correct postition.
        """
        self.assertEqual(MainWindow.objectName(), "MainWindow")
        self.assertEqual(MainWindow.size(), QtCore.QSize(231, 208))
        self.assertEqual(centralwidget.objectName(), "centralwidget")
        self.assertEqual(group_box_subtitle.geometry(), QtCore.QRect(20, 20, 191, 131))
        self.assertEqual(group_box_subtitle.objectName(), "group_box_subtitle")
        self.assertEqual(label_patientid.geometry(), QtCore.QRect(10, 30, 71, 21))
        self.assertEqual(label_patientid.objectName(), "label_patientid")
        self.assertEqual(line_edit_patientid.geometry(), QtCore.QRect(80, 30, 101, 20))
        self.assertEqual(line_edit_patientid.objectName(), "line_edit_patientid")
        self.assertEqual(push_button.geometry(), QtCore.QRect(110, 100, 71, 20))
        self.assertEqual(push_button.objectName(), "push_button")
        self.assertEqual(label_birthyear.geometry(), QtCore.QRect(10, 60, 71, 21))
        self.assertEqual(label_birthyear.objectName(), "label_birthyear")
        self.assertEqual(line_edit_birthyear.geometry(), QtCore.QRect(80, 60, 101, 20))
        self.assertEqual(line_edit_birthyear.objectName(), "line_edit_birthyear")
        self.assertEqual(menubar.geometry(), QtCore.QRect(0, 0, 231, 18))
        self.assertEqual(menubar.objectName(), "menubar")
        self.assertEqual(MainWindow.menuBar(), menubar)
        self.assertEqual(statusbar.objectName(), "statusbar")
        self.assertEqual(MainWindow.statusBar(), statusbar)


    def test_open_window(self):
        """
        This function test whether the "open_window" function get a right values from text
        editor for patient_id & birth year. Check if pdf is generated by the function.
        Check if the new window is opened after calling the function.
        """
        self.window = QtWidgets.QMainWindow()
        self.ui = UiOutput1Window(self.window, 61, 1947)
        line_edit_patientid.setText("61")
        line_edit_birthyear.setText("1947")
        patient_id = int(line_edit_patientid.text())
        birth_year = int(line_edit_birthyear.text())
        pdf_get_report(patient_id, birth_year)
        self.window.show()

        self.assertEqual(patient_id, int(line_edit_patientid.text()))
        self.assertEqual(birth_year, int(line_edit_birthyear.text()))
        self.assertTrue(self.window.isActiveWindow)
        self.assertTrue(os.path.isfile('html2pdf.pdf'))

    def test_retranslate_ui(self):
        """
        This function test whether the "test_retranslate_ui" set a correct title/text
        for each attributes.
        """
        self.assertEqual(MainWindow.windowTitle(), "MainWindow")
        self.assertEqual(group_box_subtitle.title(), "Health Record Input")
        self.assertEqual(label_patientid.text(), "Patient ID")
        self.assertEqual(push_button.text(), "Search")
        self.assertEqual(label_birthyear.text(), "Birth Year")


if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    MainWindow.setObjectName("MainWindow")
    MainWindow.resize(231, 208)
    centralwidget = QtWidgets.QWidget(MainWindow)
    centralwidget.setObjectName("centralwidget")
    group_box_subtitle = QtWidgets.QGroupBox(centralwidget)
    group_box_subtitle.setGeometry(QtCore.QRect(20, 20, 191, 131))
    font = QtGui.QFont()
    font.setPointSize(15)
    group_box_subtitle.setFont(font)
    group_box_subtitle.setObjectName("group_box_subtitle")
    label_patientid = QtWidgets.QLabel(group_box_subtitle)
    label_patientid.setGeometry(QtCore.QRect(10, 30, 71, 21))
    font = QtGui.QFont()
    font.setPointSize(10)
    label_patientid.setFont(font)
    label_patientid.setObjectName("label_patientid")
    line_edit_patientid = QtWidgets.QLineEdit(group_box_subtitle)
    line_edit_patientid.setGeometry(QtCore.QRect(80, 30, 101, 20))
    font = QtGui.QFont()
    font.setPointSize(10)
    line_edit_patientid.setFont(font)
    line_edit_patientid.setObjectName("line_edit_patientid")
    push_button = QtWidgets.QPushButton(group_box_subtitle)
    push_button.setGeometry(QtCore.QRect(110, 100, 71, 20))
    font = QtGui.QFont()
    font.setPointSize(10)
    push_button.setFont(font)
    push_button.setObjectName("push_button")
    label_birthyear = QtWidgets.QLabel(group_box_subtitle)
    label_birthyear.setGeometry(QtCore.QRect(10, 60, 71, 21))
    font = QtGui.QFont()
    font.setPointSize(10)
    label_birthyear.setFont(font)
    label_birthyear.setObjectName("label_birthyear")
    line_edit_birthyear = QtWidgets.QLineEdit(group_box_subtitle)
    line_edit_birthyear.setGeometry(QtCore.QRect(80, 60, 101, 20))
    font = QtGui.QFont()
    font.setPointSize(10)
    line_edit_birthyear.setFont(font)
    line_edit_birthyear.setObjectName("line_edit_birthyear")
    MainWindow.setCentralWidget(centralwidget)
    menubar = QtWidgets.QMenuBar(MainWindow)
    menubar.setGeometry(QtCore.QRect(0, 0, 231, 18))
    menubar.setObjectName("menubar")
    MainWindow.setMenuBar(menubar)
    statusbar = QtWidgets.QStatusBar(MainWindow)
    statusbar.setObjectName("statusbar")
    MainWindow.setStatusBar(statusbar)

    _translate = QtCore.QCoreApplication.translate
    MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
    group_box_subtitle.setTitle(_translate("MainWindow", "Health Record Input"))
    label_patientid.setText(_translate("MainWindow", "Patient ID"))
    push_button.setText(_translate("MainWindow", "Search"))
    label_birthyear.setText(_translate("MainWindow", "Birth Year"))

    unittest.main()
